package H6;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Scanner;
import java.util.Set;
import java.util.TreeSet;

public class DataForYou {

    public static void main(String[] args)  {
    	
    	List<String> al= new ArrayList<>();
		try (Scanner skener = new Scanner(new File("DataForYou1.txt"))){
			
			while(skener.hasNextLine()) {
				String pom = skener.nextLine();
				String[] pole = pom.split(" ");
				for (int i = 0; i < pole.length; i++) {
					if(pole[i].trim().length() != 0) {
						al.add(pole[i].trim());
					}
				}
	    		//System.out.println(skener.nextLine());
			}
			//skener.nextLine();
		} catch (FileNotFoundException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
    	System.out.println(al);
    	
    	
    	
    	
    	//---------------------------------- toto je z cvicenia 06
        //List<String> al = Arrays.asList(spoluziaci);
        Set<String> s = new TreeSet<>(al);
        System.out.println("Pocet roznych: " + s.size());
        System.out.println(s);

        al.sort((s1,s2) -> Integer.compare(s1.length(),s2.length()));
        System.out.println(al);

        Map<String, Integer> hm = new HashMap<>();
        for(String str : al){
            if (!hm.containsKey(str)){
                hm.put(str, 1);
            }
            else{
                hm.put(str, hm.get(str)+1);
            }

        }

        TreeSet<Integer> set = new TreeSet<>(hm.values());
        Integer last =  set.last();

        System.out.println("Najcastejsi prvok: " + last);

        Set<String> keys = hm.keySet();
        for(String k : keys){
            if(hm.get(k) == last){
                System.out.println(k);
            }
        }

        hm.forEach((k,v) -> {if(v == last) System.out.println(k);});
        
    }

    public static final String[] spoluziaci = {
            "Lubomir", "Jana","Ivan","Pedro","Zofia","Filomena","Ivan","Maria","Jano","Zuzana","Ivan","Dagmar","Zuzana","Florian","Filomena","Filomena",
            "Petra","Luba","Luba","Ivan","Zuzana","Sona","Luba","Florian","Maria","Filomena","Florian","Kamil","Lubomir","Rexana","Karol",
            "Peter","Zuzana","Lubomir","Petra","Dagmar","Florian","Jana","Ivan","Filomena","Filomena","Zofia","Petra","Kamil","Filomena","Zuzana",
            "Sona","Petra","Dagmar","Filomena","Zofia","Jano","Maria","Zuzana","Zofia","Pista","Maria","Zofia","Pedro","Filomena","Pedro",
            "Sona","Florian","Filomena","Luba","Zuzana","Maria","Ivan","Pedro","Maria","Florian","Sona","Petra","Pista","Lubomir","Jano",
            "Zuzana","Maria","Jano","Filomena","Sona","Rexana","Dagmar","Peter","Florian","Jano","Jano","Petra","Zuzana","Florian","Jano",
            "Florian","Peter","Florian","Kamil","Petra","Zofia","Pista","Sona","Florian","Jana","Petra","Kamil","Florian","Maria","Filomena",
            "Dagmar","Pista","Sona","Pista","Jana","Jano","Kamil","Ivan","Jana","Filomena","Petra","Jano","Pedro","Karol","Maria",
            "Zofia","Pedro","Petra","Peter","Kamil","Jana","Jana","Lubomir","Florian","Rexana","Kamil","Lubomir","Sona","Ivan","Petra",
            "Rexana","Filomena","Pedro","Pedro","Luba","Filomena","Pedro","Zofia","Dagmar","Kamil","Petra","Pedro","Maria","Zofia","Sona",
            "Filomena","Zofia","Dagmar","Luba","Rexana","Maria","Peter","Zuzana","Ivan","Zuzana","Jano","Lubomir","Luba","Filomena","Maria",
            "Pedro","Ivan","Zuzana","Zuzana","Pista","Karol","Kamil","Kamil","Florian","Jana","Jana","Filomena","Ivan","Zuzana","Jana",
            "Filomena","Sona","Pista","Jano","Karol","Ivan","Pedro","Florian","Zuzana","Filomena","Lubomir","Luba","Ivan","Petra","Rexana",
            "Sona","Luba","Kamil","Florian","Filomena","Dagmar","Ivan","Dagmar","Pedro","Pedro","Pista","Zofia","Zofia","Zuzana","Lubomir",
            "Ivan","Maria","Dagmar","Filomena","Pista","Filomena","Pedro","Jano","Maria","Luba","Pedro","Pedro","Florian","Florian","Maria",
            "Zuzana","Jano","Karol","Rexana","Zuzana","Jana","Pedro","Jano","Sona","Maria","Filomena","Rexana","Pedro","Pista","Kamil",
            "Sona","Pedro","Lubomir","Dagmar","Peter","Jana","Jana","Ivan","Pedro","Jano","Maria","Florian","Pedro","Rexana","Filomena",
            "Karol","Petra","Jano","Pista","Jano","Zofia","Jano","Lubomir","Filomena","Dagmar","Florian","Maria","Zofia","Rexana","Rexana",
            "Peter","Luba","Karol","Maria","Jana","Peter","Sona","Pedro","Filomena","Zuzana","Petra","Ivan","Jano","Zuzana","Pedro",
            "Pista","Jano","Pista","Pedro","Rexana","Jano","Maria","Jano","Zofia"};

    public static final String[] spoluziaciCelejSkoly = {
            "Aaron","AarÃ³n","Abadon","Abdon","AbdÃ³n","Abel","Ã�bel","Abelard","AbelÃ¡rd","Abelardo","Abele","Abelone","Abigael","Abigail","AbigÃ©l",
            "Abraham","AbrahÃ¡m","Ã�brahÃ¡m","Abram","Abramo","Absalom","Absalon","Absolon","AbsolÃ³n","Ada","Adalbert","Adalberta","Adalbertina","Adalberto","AdalbertÃ½na",
            "Adalbrecht","Adalwin","Adam","Ã�dÃ¡m","Adamo","AdÃ¡n","Adda","Adeinaida","Adeineid","Adel","AdÃ©l","AdÃ©la","AdÃ©la","Adelaida","Adelaide",
            "AdÃ©laide","Adelajda","Adelbert","AdÃ©le","Adile","Adelhilda","AdÃ©lia","Adelina","Adelina","Adelinda","Adelinde","Adeline","Adeltraud","Adeltrude","Adin",
            "Adina","AdlÃ©ta","Adolf","Adolfa","Adolfina","Adolfina","Adolfme","Adolfo","Adolph","Adolpha","Adolphe","Adolphina","Adolphine","Adolphus","AdorjÃ¡n",
            "Adria","Adriaan","Adrian","AdriÃ¡n","Adriana","AdriÃ¡na","Adriani","Adriano","Adriauna","Adrien","Adriena","Adrienn","Adrienna","Adrienne","Adrijan",
            "Adrijana","Aegidius","Aemilia","Aemilius","Afabella","Afanas","Afanasij","Afanasija","Afanka","Afda","Afeta","Afete","Afetha","Afette","Afiadna",
            "Afiadni","Afiana","Afina","Afra","Afranija","Africo","Agafja","Agafon","Agafonik","Agata","AgÃ¡ta","Agate","Agatha","Agathe","Agathon",
            "Agatokleia","Agaton","AgatÃ³n","Agatone","Agatonike","Aggel","Ã„gid","Ã„gidius","Aglaia","Aglaja","AglÃ¡ja","Agnes","Agnis","Ã�gnes","Agnesa",
            "Agnese","Agnessa","AgneÅ¡a","Agneta","Agnete","Agnethe","Agnieszka","Ã�gosta","Agostino","Ã�goston","AgÃ³ta","Agueda","Achil","Achiles","Achill",
            "Achille","Achilleas","Achilles","Achillij","Aidan","Aiden","Aimar","AimÃ©e","Ajrin","Akim","Aksel","Alabhaois","AladÃ¡r","Alain","Alaios",
            "Alajos","Alan","AlÃ¡n","Alana","Alanis","Alano","Alanus","Alasdair","Alastair","Alba","Alban","Albana","Albano","Albanus","Albena",
            "Albert","Alberta","Alberte","Albertin","Albertina","Albertina","Albertini","Alberto","AlbertÃ½n","Albertyna","Albertyna","Albin","AlbÃ­n","Albina","Albina",
            "Albine","Albino","Albinus","Albrecht","Albyn","Alda","Alde","Aldo","Alec","Alejandra","Alejandro","Aleks","Aleksa","Aleksander","Aleksandr",
            "Aleksandra","Aleksansdar","Aleksej","Aleksi","Aleksija","Aleksina","Aleksis","Aleksy","Alen","Alena","Alena","Alesia","Alessandra","Alessandro","Alessia",
            "Alessio","Alesszia","AleÅ¡","AleÅ¡a","AleÅ¡ka","Aletea","Alithe","Alethea","AlÃ©thea","Aletheia","Alex","Alex","Alexa","Alexander","Alexandr",
            "Alexandra","Alexandre","Alexandre","Alexandros","Alexandru","Alexej","Alexia","Alexie","Alexine","Alexis","Alexis","Alexius","Alfons","Alfonso","Alfonz",
            "Alfred","AlfrÃ©d","Alfreda","AlfrÃ©da","Alfredas","Alfredo","Alfredus","Alfrida","AliadnÃ©","Alica","Alice","Alicia","Alicja","Alida","AliÃ©nor",
            "Alina","Aline","Alisa","Alise","Alisha","Alisija","Alison","Alisson","Alithea","Alithia","Alitigone","Aliz","Alkaterini","Allan","Allee",
            "Alleen","Alleen","Allen","Allena","Allene","Alleta","Allette","Allison","Alma","Almaricus","Almi","Almida","Almidija","Almlina","Alna",
            "Alodie","Aloin","Alois","Aloisa","Aloisia","Aloisie","Aloisio","Aloisius","Alojz","Alojza","Alojzia","Alojzie","Alojzja","Alojzy","Alonso",
            "Aloys","Aloysia","Aloysius","Alphonse","Alphonso","AltÃ©inis","Altemija","Altemis","Altemisa","AltÃ©mise","Altemisz","Altulini","Altylini","Aluin","Alva",
            "Alvar","Alvaro","Alvian","AlviÃ¡n","Alvin","Alvina","Alvino","Alwin","Alwina","Alwyn","Alysha","AlÅ¾bita","AlÅ¾bita","Amabel","AmadÃ©",
            "Amadea","Amadea","Amadej","Amadeo","Amadeu","Amadeus","Amadeusz","Amadia","Amado","Amalberga","Amaldeia","Amalia","AmÃ¡lia","AmÃ¡lie","AmÃ¡lie",
            "AngÃ©lique","Angell","Angelo","Angelos","Angelus","Anghel","Angus","Angyalos","Aniela","Aniello","Anika","AnikÃ³","Aniol","Anisja","Anissa",
            "Anita","Anja","Ann","Anna","Annabel","Annabela","Annabella","Annabelle","Anne","Annetta","Annette","Anni","Annie","Annika","Annouk",
            "Anny","Anouk","Ansel","Anselm","Anselma","Anselme","Anselmo","Anshelm","Antal","Ante","Antea","Anteia","Antheia","Anthony","Anthula",
            "AntÃ­a","Antigona","Antim","Antin","Antoan","Antoine","Antoinette","Antokleia","Anton","Antonetta","Antoni","Antonia","Antonia","Antonida","Antonie",
            "Antonij","Antonija","Antonije","Antonin","AntonÃ­n","AntonÃ­na","AntonÃ­na","Antonini","Antonino","Antonio","Antonios","Antonis","Antonius","Antony","Antula",
            "Antun","AnuÅ¡e","Anzelm","Anzelma","Apolena","Apoliena","Apolka","Apolline","Apollo","Apollonia","ApollÃ³nia","Apollonie","Apollonija","Apolonia","ApolÃ³nia",
            "Apolonie","Arabela","ArabeUe","Araldo","Aram","Aretta","Archip","Ariadni","Arian","Ariane","Arianna","Arianne","Ariel","Ariela","Ariella",
            "Arielle","Arijadna","Arika","Aristid","Aristide","Aristides","Arisztid","ArkÃ¡d","Arkadij","Arkadius","Arkady","Arman","Armand","Armando","Armin",
            "Ã�rmin","Arminio","Arminius","Armyn","Arnaldo","Arnau","Arnaud","Arnault","Arne","Arno","ArnÃ³","Arnold","Arnolda","Arnolde","Arnoldia",
            "Arnoldo","ArnoÅ¡t","ArnoÅ¡ta","ArnoÅ¡?ka","Arnoult","Arnout","Aron","Ã�ron","Aronne","Arpad","ArpÃ¡d","Ã�rpÃ¡d","Arsene","Arsen","Arsenij",
            "Arsenije","Arsenio","Arsenios","Arsenius","Arseniusz","Artem","Arteme","Artemida","Artemij","Arthur","Arthurus","Artim","Ar?om","Artturi","Artur",
            "ArtÃºr","Arturo","ArtuÅ¡","Arzen","ArzÃ©n","Ashley","Ashley","Askold","Aspasia","Aspasie","Aster","Astra","Astrid","Astrida","Astryda",
            "Asztrid","Atanas","Atanasia","Atanasie","Atanasij","Atanasija","Atanasije","Atanasio","AtanÃ¡Å¡","AtanÃ¡Å¡ka","AtanÃ¡z","AtanÃ¡zia","AtanÃ¡zie","Atanazja","Atanazy",
            "Atena","Atene","AtÃ©nÃ©","Athana","Athanase","Athanasia","Athanasie","Athanasios","Athanasius","AthÃ©na","AthÃ©na","Athene","Athina","Atila","Atilla",
            "Atina","Attila","Attilo","Aubin","Aubine","Audra","Audrey","August","Augusta","Augusta","Auguste","Auguste","Augustin","AugustÃ­n","Augustina",
            "Augustina","Augustina","Augustine","Augustinus","Augusto","Augustus","Augustyn","AugustÃ½n","Augustyna","AugustÃ½na","Auguszta","Auni","Aura","Aurea","Aurel",
            "AurÃ©l","Aurela","Aureli","Aurelia","AurÃ©lia","Aurelian","AureliÃ¡n","AurÃ©liÃ¡n","Aurelie","AurÃ©lie","Aurelij","Aurelija","Aurelio","Aurelius","Aurora",
            "Aurora","Aurooe","Austin","Avdon","Avelina","Aveline","Avgust","Avgusta","Avgustin","Avraam","Avraamij","Avram","Avrelij","Avrelija","Avrora",
            "Axel","Aya","Ayleen","Aylin","Babbette","Babeta","Babett","Babette","BalÃ¡zs","Baldassare","BÃ¡lint","Baltasar","Baltazar","BaltazÃ¡r","Balthasar",
            "Balthazar","BÃ¡ra","BarabÃ¡s","BarabÃ¡Å¡","Barak","Barbara","Barbara","BarbÃ©","Barber","Barbora","Barbra","Barbro","Barna","Barnaba","Barnabas",
            "BarnabÃ¡s","BarnabÃ¡Å¡","BarnabÃ©","Barnaby","Barnard","Barney","Barrabas","Bart","BarthÃ©lemy","BartholomÃ¤us","BartholomÃ©","Bartholomeus","Bartholomew","Bartolomej","Bartolomij",
            "Bartolomiej","Bartolomij","Basil","Basile","BasilÃ©o","Basileus","Basilij","Basilio","Basilius","Bastian","Bastien","Bazil","Bazyli","Bea","Beat",
            "Beata","BeÃ¡ta","Beate","Beato","Beatrica","Beatrice","BÃ©atrice","Beatrisa","Beatrix","Beatriz","Beatrycza","Beatus","Bedros","Bedoich","Bedoicha",
            "BedoiÅ¡ka","Beitris","Bela","BÃ©la","Bila","Belinda","Bell","Bella","Belle","Biloslava","BiluÅ¡e","Ben","Beoadik","Benedek","Benedetta",
            "Benedetto","Benedict","Benedicta","Benedicte","Benedicto","Benedikt","Benedikta","Benedikte","Benedita","Benedykt","Benedykta","Benet","Benett","Bengta","BÃ©ni",
            "Beniamin","Beniamino","Benigna","Benigni","Benita","Benito","Benjamin","BenjamÃ­n","BenjÃ¡min","BenkÃ¶","Bennet","Bennie","Benno","BennÃ³","Bennone",
            "Benny","Beno","BenÃ¶","Beoo","Benoit","Benoite","Benon","Berardo","Berenice","BÃ©rÃ©nice","Berenika","Berenike","BerenikÃ©","Bergit","Berit",
            "BernÃ¡","Bernaard","Bernadeta","Bernadette","Bernard","Bernarda","Bernardeta","Bernardetta","Bernardette","Bernardin","Bernardina","Bernardine","Bernardo","Bernardus","BernardÃ½na",
            "Bernat","BernÃ¡t","Bernhard","Bernharda","Bernhardina","Bernhardine","Bert","Berta","Bertalan","Berte","Bertel","Bertha","Berthe","Berthold","Bertholda",
            "Bertholdine","Bertil","Bertina","Bertold","Bertolda","Bertoldo","Bertram","BertrÃ¡n","Bertrand","Bertrando","Beryl","Beryll","Bess","Bessie","Bessy",
            "Bita","Betty","Bianca","Bianca","Bianka","Bibi","Bibiana","BibiÃ¡na","Bibijana","Bijanka","Birgid","Birgit","Birgita","Birgitt","Birgitta",
            "Birgitte","Bistar","Bivoj","Bjela","Blago","Blagomila","Blagomir","Blagomira","Blagoslav","Blahomil","Blahomila","BlahomÃ­r","BlahomÃ­ra","Blahoslav","Blahoslava",
            "BlahuÅ¡e","Blaise","Blanch","Blanche","Blanka","Blase","Blasios","Blasius","BlaÅ¾ej","BlaÅ¾eja","BlaÅ¾ejka","BlaÅ¾en","BlaÅ¾ena","Bogdan","Bogdana",
            "Bogislav","Bogislava","Bogohval","Bogoljub","Bogomil","Bogomila","Bogomir","Bogomira","Bogoslav","Bogoslava","BogoÅ¡","Boguchval","Boguchwal","Bogumil","Bogumila",
            "Bogumila","Boguslav","Boguslava","BoguslÃ¡vo","Boguslaw","Boguslawa","Bogusz","Bohdan","Bohdana","Bohdanka","Bohomil","Bohuchval","Bohumir","Bohumil","Bohumila",
            "BohumÃ­r","BohumÃ­ra","Bohun","Bohuna","Bohunka","Bohuslav","Bohuslava","BohuÅ¡","BohuÅ¡e","Bochmir","Bojan","Bojana","BojÃ¡na","Bojeslav","Bojislav",
            "Bojislava","BÃ³jka","BojmÃ­r","BoldizsÃ¡r","Bolek","BolemÃ­r","Boleslav","Boleslava","Boleslaw","Boleslawa","Boljemir","Boljeslav","Bona","Bonifac","BonifÃ¡c",
            "Boniface","Bonifacij","Bonifacio","Bonifacius","Bonifacy","Bonifatij","Bonifatius","Bonifaz","BorbÃ¡la","Borek","Borimir","BorimÃ­r","Boris","Borisav","Borislav",
            "Borislav","Borislava","Borislava","Borisz","Borjan","Borko","Borna","Boro","Borys","Boryslaw","Boryslawa","Borzyslaw","Booek","Booislav","Booivoj",
            "BozsidÃ¡r","BoÅ¾ana","BoÅ¾ena","BoÅ¾ena","BoÅ¾etech","BoÅ¾etich","BoÅ¾eticha","BoÅ¾eticha","BoÅ¾idar","BoÅ¾idara","BoÅ¾ika","BoÅ¾in","BoÅ¾ina","BoÅ¾islav","BoÅ¾islava",
            "BoÅ¾ko","Brandon","Branija","Branimer","Branimir","BranimÃ­r","Branimira","BranimÃ­ra","Branisav","Branislav","Branislava","Branka","Branko","Bratislav","Bratislava",
            "Brenda","Brendan","Bret","Bretislav","Brett","Brian","Briano","Bridget","Brighid","Brigida","Brigit","Brigita","Brigitta","Brigitte","Brit",
            "Brita","Britanij","Britt","Britta","Brjaeislav","Brjaeislava","Brooa","Bronik","Bronia","Bronislav","Bronislava","Bronislaw","Bronislawa","Bronislawa","Bronja",
            "Bruce","Bruna","Brungilda","Brunhild","Brunhilda","Brunhilde","Bruno","BrÃºnÃ³","Brunon","Bryan","Brygida","Boecislava","Boetislav","Boetislava","Boetislava",
            "Budimil","BudimÃ­r","Budislav","Budivoj","Budzimir","Budzislaw","Burga","Burghild","Burghilde","Burglind","Burglinde","Burgunda","Burgunde","BystrÃ­k","Cacilie",
            "Caecilia","Caesar","Caetano","Caitlin","Cajetanus","Calipso","Calum","Calypso","Cameron","Camila","Camill","Camilla","Camille","Camillo","Camillus",
            "Camilo","CamiUe","Canute","Cara","Carina","Carine","Carl","Carla","Carleen","Carli","Carlina","Carlo","Carlos","Carlota","Carlotta",
            "Carmel","Carmela","Carmen","Carol","Carol","Carola","Carole","Carolin","Carolina","Caroline","Carolyn","Casandra","CÃ¤sar","Casey","Casey",
            "Casiano","Casimir","Casimiro","Caspar","Cassandra","Cassandre","Cassian","Cassie","Cassio","Cassius","Castor","CÃ¡stor","Castore","CÃ¡stulo","Castulus",
            "Catalina","Catarina","Caterina","Catharina","Catherine","Cathia","Catia","Catriona","Cecil","Cecile","CÃ©cile","Cecilia","CecÃ­lia","CeciliÃ¡n","Cecilie",
            "CecÃ­lie","Cecilija","Cecilio","CÃ©cille","Cecily","Cecylia","Cecyliusz","Cedric","CÃ©dric","Cedrik","CÃ©lanie","Celany","Celestin","CelestÃ­n","Celestina",
            "CelestÃ­na","Celestine","Celestino","Celestyn","CelestÃ½n","Celestyna","CelestÃ½na","Celesztin","Celesztina","Celia","CÃ©lia","Celie","Celina","Celini","CÃ©line",
            "Cenzo","Cesar","Cesare","CÃ©sare","CÃ©sareo","Ceslava","Cestimira","Cezar","CÃ©zar","CÃ©zÃ¡r","Cezariusz","Cezary","Cilla","Cinda","Cindy",
            "Cinisula","Cintia","Cinystina","CipriÃ¡n","Cipriano","Cirila","Cirilija","Cirilla","Cirillo","Cirilo","Claire","Clara","Clarika","Clarissa","Clarisse",
            "Clark","Claoe","Claud","Claude","Claude","Claudia","Claudie","Claudina","Claudio","Claudius","Clemens","Clement","ClÃ©ment","Clemente","Clementia",
            "Clementina","Clementine","Cleopatra","Clotario","Clothilde","Clotilda","Clotilde","Coleman","CÃ¶lestin","CÃ³lestine","CÃ¶lestinus","Coleta","Coletta","Colette","Colin",
            "CÃ³lina","Colman","Coloman","Colomba","Colombano","Colombe","Colombina","Colombino","Colombo","Colum","Columba","Columban","Columbanus","Columbia","Columbina",
            "Columbine","Cona","Conner","Connor","Conrad","Conrado","Conroy","Constanca","Constance","Constancia","Constans","Constansa","Constant","Constanta","Constantin",
            "Constantine","Constantino","Constantinus","Constanza","Constanze","Constanzo","Consuela","Cora","Cordelia","CordÃ©lie","Cordula","CÃ³rdula","Cordule","Corina","Corinna",
            "Corinne","Cormac","Corneille","Cornelia","CornÃ©lie","Cornelio","Cornelis","Cornelius","Corona","Corrado","Cosme","Cosmo","Craig","CrÃ©pin","Crescentia",
            "Crispin","CrispÃ­n","Crispino","Crispinus","Crispus","Cristalina","Cristian","CristiÃ¡n","Cristiano","Cristina","Cristinha","Cristino","Cristo","Cristobal","Cristofor",
            "Cristoforus","Ctibor","Ctibora","CtimÃ­r","Ctirad","Ctirada","Ctislav","Ctislava","Cunegond","Cunegonda","CunÃ©gonde","Cunegunda","Cunegundes","Curd","Curt",
            "Curzio","Cveta","Cvetan","Cvetana","Cvetimira","Cvetislav","Cvetislava","Cvetomir","Cvetomira","Cvetoslava","Cynthia","Cyntia","Cyntie","Cyprian","CypriÃ¡n",
            "Cyprianus","Cyprien","Cyril","Cyrila","Cyrilka","Cyrill","Cyrilla","Cyrille","Cyrillus","Cyrus","Cyryla","Czeslaw","Czeslawa","Easlav","Easlava",
            "Eedomir","Eenik","Eeoka","Eeslav","Eeslava","Eestimir","Eestislav","EestmÃ­r","EestmÃ­ra","Eistoslav","Eistoslava","Daan","Dafne","DafnÃ©","Dafni",
            "Dag","Dagmar","Dagmara","Dagobert","Dagoberto","Dagomaro","Dahl","Dahl","Dahlia","Daisy","Dajana","Dajena","Dalebor","Dalemil","Dalemir",
            "Dalia","DÃ¡lia","Dalibor","Dalibora","Dalida","Dalidia","Dalie","Dalija","Dalila","DÃ¡lila","Dalimil","Dalimila","DalimÃ­r","DalimÃ­ra","Dalma",
            "Dalmacija","Dalmata","Dalmatinka","Dalmazia","Dalmira","DalmÃ­ra","Damaris","DÃ¡maris","Damia","Damiaan","Damian","DamiÃ¡n","Damiana","DamiÃ¡na","Damiane",
            "Damiano","Damianos","Damianus","Damien","Damijan","Damijana","Damir","Damjan","DamjÃ¡n","Damjana","Damon","Dan","Dana","Danae","DanaÃ©",
            "Danai","Danail","Danaila","Danel","DaneÅ¡","Danica","Danice","Daniel","DÃ¡niel","Daniela","Daniele","Daniella","Danielle","Daniil","Daniila",
            "Danijel","Danijela","Danika","Danila","Danila","Danilo","Danitza","Danka","Danko","Dankrad","Dankret","Danny","Dano","DanuÅ¡e","Danuta",
            "Danylo","Daphne","DaphnÃ©","Dara","Darcy","Darek","Darel","Daren","Daria","DÃ¡ria","Darie","Darie","Darien","Darij","Darija",
            "Darije","Darina","Darinka","Dario","DarÃ­o","Darius","DÃ¡rius","Dariusz","Darja","DÃ¡rjÃºÅ¡","Darko","Darleen","Darlena","Darlene","Daro",
            "Darrel","Darrell","Darren","Darrene","Darryl","DaruÅ¡e","Darya","Daryl","DÃ¡Å¡a","DÃ¡Ãºd","Dave","David","DÃ¡vid","Davida","Davide",
            "Davina","Davinia","Davita","Davor","Davud","Davy","Dawid","Dean","Deana","Debora","DebÃ³ra","Deborah","DÃ©borah","Deidre","Deinela",
            "Deinse","Dejan","Dejana","DelfÃ­na","DelfÃ­ne","Delia","DÃ©lia","Delie","Delija","Dilila","Delphina","Delphine","Demeter","Demeter","Demetria",
            "Demetrio","Demetrios","Demetrius","DÃ©mÃ©trius","Demi","Demjan","DÃ©nes","Denica","Deniel","Denis","Denisa","Denisija","Dennis","Denny","Denys",
            "Deodoro","Dipold","Derek","Derica","Derika","Derrick","Desanka","Desideria","Desiderij","Desiderije","Desiderio","Desiderius","DÃ©sirÃ©","DÃ©sirÃ©e","Desmond",
            "Despina","Ditmar","Detre","Detrich","Ditoich","Deva","Devana","Divana","Dezider","Dezidera","Deziderija","DezsÃ¶","Dezyderia","Dezyderius","Dezydery",
            "Dia","Diana","Diana","Diandra","Diani","Dianne","Dick","Didda","Diderik","Didier","Didrik","Diede","Dieder","Diederik","Diego",
            "Dietbald","Dieter","Diethild","Diethilde","Dietlind","Dietlinde","Dietmar","Dietrich","Dijana","Dimitar","Dimitr","Dimitra","Dimitri","Dimitrij","Dimitrije",
            "Dimitrina","Dimitrios","Dimitris","Dimitrula","Dina","Dinah","Dinka","Dino","Dionisia","Dionisio","Dioniza","DionÃ­zia","Dionizij","Dionizija","Dionizije",
            "Dionizja","Dionizy","Dionys","Dionysia","Dionysie","Dionysija","Dionysius","DionÃ½sos","DionÃ½z","DionÃ½zie","DionÃ½zka","Dionyzy","Disma","Dismas","Dita",
            "Ditmar","DitmÃ¡r","Ditta","Ditte","DiviÅ¡","Dlugomil","Dlugomir","DluhoÅ¡","Dmitrij","Dmitro","DMÅ¡ka","Dobra","Dobrava","Dobrivoj","Dobromil",
            "Dobromila","Dobromila","Dobromir","DobromÃ­r","Dobromira","DobromÃ­ra","Dobrosav","Dobroslav","Dobroslava","Dobroslaw","Dobroslawa","DobruÅ¡e","Doboena","Dolores","Doloris",
            "DolÃ³resz","DolorÃ³za","Domenica","Domenico","Domenika","Domingo","Dominic","Dominica","Dominica","Dominick","Dominicus","Dominik","Dominika","Dominikus","Dominique",
            "Dominique","Domniki","Domokos","Domonkos","Don","Dona","Donal","Donald","Donalda","Donaldo","Donall","Donar","Donat","DonÃ¡t","Donata",
            "DonÃ¡ta","Donatela","Donatella","Donato","Donatos","Donatus","Donica","Donika","Donna","Donnel","Donnell","Donovan","Dora","Dora","Dore",
            "Doreen","Dorett","Dorette","Dorian","DoriÃ¡n","Dorijan","Doris","Dorisa","Dorit","Dorita","Dorith","Dorius","Dorka","Dorkas","Dorofeja",
            "Dorota","Dorotea","Doroteja","Dorothea","Dorothy","Dorotka","Dorottya","Dorrit","Doubrava","Doubravka","Draga","Dragan","Dragana","Dragica","Dragimir",
            "Drago","Dragoljub","Dragoljuba","Dragomil","Dragomila","Dragomir","Dragomira","Dragosav","Dragosava","Dragoslav","DragoslÃ¡va","Dragoslaw","DragoÅ¡","Dragotin","Dragutin",
            "DragutÃ­n","Draho3ub","Drahomil","Drahomila","DrahomÃ­r","DrahomÃ­ra","Drahoo","Drahoslav","Drahoslava","DrahoÅ¡","DrahotÃ­n","Drahotina","DrahuÅ¡e","Drogomila","Drogomir",
            "Drogoslawa","Drogosz","DÃºbrava","Dubravka","Duchoslav","Duchoslava","Dulce","Dulcia","Dulcie","Dulcinea","Dulcinela","Dumitru","Duna","Duncan","Dunja",
            "Dustin","Duszan","DuÅ¡an","DuÅ¡ana","DuÅ¡ka","DuÅ¡ko","Dylan","Dymitr","Dysmas","Dyzma","DÅ¾ani","Ebba","Ebrahim","Ecaterina","Eckbert",
            "Ed","Eda","Eda","Edda","Eddi","Eddie","Eddy","Edeltraud","Edeltrauda","Edeltraude","Edeltrud","Edeltruda","Edeltrude","Edeltrudis","Edgar",
            "EdgÃ¡r","Edgard","Edgardo","Edgaro","Edilberto","Edit","Edita","Edith","Ã‰dith","Editha","Edmond","Edmonda","Edmondo","Edmund","Edmunda",
            "Edmundo","Edmundus","Edna","Edoardo","Edon","Ã‰douard","Ã‰douardine","Eduard","Eduarda","Eduarde","Eduarde","Eduardine","Eduardine","Eduardo","Eduardus",
            "Eduino","Edultride","Edvard","EdvÃ¡rd","Edvarda","Edviga","Edvige","Edvin","EdvÃ­n","Edvina","Edvino","Edward","Edwarda","Edwardine","Edwige",
            "Edwin","Edwina","Edwine","Edyta","Efi","Efraim","Efrem","Efrosini","Efrosynija","Eftalia","Eftimia","Eftymia","Egbert","Egedij","Egedije",
            "Egid","Egidij","Egidion","Egidius","EgÃ­dius","Egmont","Egmund","Egon","Egona","Egonda","Egondina","Egonia","Egyed","Eileen","Eirik",
            "Ekaterina","Ekaterini","Ela","Ã‰laine","Elea","Eleanor","Eleazar","ElÃ©azar","Eleazaro","Electra","Elefterios","Eleftherios","Elektra","ElemÃ­r","Elen",
            "Elena","Eleni","Eleni","Eleonor","Eleonora","Eleonora","Eleonooe","Eleonooe","Eleuterios","Eleutherios","Elfreda","Elfrida","ElfrÃ­da","Elfried","Elfrieda",
            "Elfriede","Elga","Eli","Elia","Eliah","Eliana","EliÃ¡na","Eliane","Ã‰liane","Elias","ElÃ­as","Ã‰liÃ¡s","Eliash","Eliasz","EliÃ¡Å¡",
            "EliÃ¡Å¡ka","Elie","Ã‰lie","EliÃ©cer","Elieser","Eliezer","EliÃ©zer","Eligio","Elijah","ElijÃ¡Å¡","Elin","Elina","Elinor","Eliodoro","Eliot",
            "Elis","Elisa","Elisabet","Elisabeta","Elisabeth","Ã‰lisabeth","Elisabetha","Elisabetta","Elisavet","Elisaveta","Elise","Elise","Ã‰lise","Ã‰lisÃ©e","Elisej",
            "Eliseo","Eliseus","Elisha","Elisha","Elissa","EliÅ¡ka","Eliza","Elizabeta","Elizabeth","Elizaveta","Elizej","Elizeus","Elizeusz","Elka","Elke",
            "Ella","Ellena","Elli","Ellina","Ellinor","Elliot","Ellis","Ellyn","Elma","Elmar","ElmÃ¡r","Elmer","Elodia","Elodie","Elpida",
            "Elpidia","Elorid","Elsa","Else","Elsie","Elvina","Elvira","ElvÃ­ra","Elwira","Elyssa","Elza","ElÅ¾bieta","Ema","Emanuel","EmÃ¡nuel",
            "Emanuela","Emanuela","Emanuele","Emanuila","Emeram","Emerentia","Emerenz","Emerenzia","Ã‰meric","Emerico","Emericus","Emerich","Emerik","Emery","Ã‰mery",
            "Emeryk","Emiel","Emil","Emila","Emile","Ã‰mile","Emilia","EmÃ­lia","Emilian","EmiliÃ¡n","Emiliana","EmiliÃ¡na","Emiliano","Emilie","Emilie",
            "EmÃ­lie","Emilij","Emilija","Emilio","Emiliusz","Emiljan","Emily","Emma","Emmanuel","Emmanuele","Emmanuelle","Emmanuil","Emmeramus","Emmerico","Emmerich",
            "Emmerik","Emmery","Emmi","Emmy","Ena","Endre","EndÅ¾e","Engelbert","Engelberto","Engracia","EnikÃ³","Enna","Enne","Enni","Enny",
            "Enoch","Ã‰nok","Enrica","Enrico","Enrichetta","Enrika","Enrique","Enriqueta","Enriquez","Enzo","EnÅ¾e","Ephraim","Erardo","Ã‰rasme","Erasmo",
            "Erasmus","Erazim","Erazm","Erazma","Erazmus","Erberto","Erhard","Erhardo","Eric","Erica","Ã‰rica","Erico","Erich","Erik","Erika",
            "Erina","Ermanno","Ermin","ErmÃ­n","Erna","Ernest","Ernesta","Ernestina","Ernestina","Ernestine","Ernesto","Ernestyna","ErnestÃ½na","Erneszta","Ernesztina",
            "ErnÃ¶","Ernst","Ervin","ErvÃ­n","Ervina","Ervina","Ervino","Erwin","Erwina","Erwine","Eryk","Eryka","ErzsÃ©bet","Ã‰saie","Esdras",
            "Esfir","Esmeralda","EsmÃ©ralda","Esperanza","Esra","Estanislao","Estanislau","Estatios","Esteban","Estefania","Estel","Estela","Estella","Estelle","Estephania",
            "Estephano","Ester","Estera","Estevan","Estevao","Esther","Estibalitz","Estrella","Eszmeralda","Eszter","Etel","Etela","Etelka","Ethel","Etheldreda",
            "Ã‰tienne","Ettore","Eudokie","EUe","EUen","Eufemia","EufÃ©mia","Eufemie","Eufrosina","Eufrosyne","Eufrozina","EufrozÃ­na","Eufrozyna","Eugen","Eugene",
            "Eugenia","EugÃ©nia","Eugenie","EugÃ©nie","Eugenio","Eugenius","Eugeniusz","Eulaalia","Eulalia","EulÃ¡lia","Eulalie","EulÃ¡lie","Eunice","Eunie","Eunika",
            "Eunike","Euphemia","EuphÃ©mie","Euphrosine","Euphrosyne","Euridika","Eurydice","EusÃ©be","Eusebia","EusÃ©bia","Eusebie","Eusebij","Eusebija","Eusebije","Eusebio",
            "Eusebius","EusÃ©bius","Euthalia","Euvaldo","EUy","Euzebia","EuzÃ©bia","Euzebiusz","Eva","Ã‰va","Evald","Evaldo","Evalyn","Evan","Evangelia",
            "Evangelina","Evangelina","EvangÃ©lina","Evangeline","Evangelista","Evangelos","Evarist","Ã‰variste","Evaristo","Evaristus","Evariszt","Evdokia","Evdokie","Eve","Evelia",
            "Eveliina","Evelin","Evelina","Evelina","Eveline","Evelio","Evelyn","Evelyna","Ã‰velyne","Evgen","Evgenija","Evita","Evlalija","Evrydiki","Evthalia",
            "Evtimia","EvÅ¾en","EvÅ¾ena","EvÅ¾enie","Ewa","Ewald","Ewaryst","Ewelina","Ewen","Eyjenia","EzdrÃ¡Å¡","EzdreÃ¡Å¡","Ezechiel","EzÃ©chiel","Ezechiele",
            "Ezechiello","Ezekiel","EzÃ©kiel","Ezequiel","Ezra","Fabia","Fabian","FabiÃ¡n","FÃ¡biÃ¡n","Fabiana","FabiÃ¡na","Fabiano","Fabianus","Fabie","Fabien",
            "Fabienne","Fabij","Fabijan","Fabijana","Fabio","Fabiola","Fabius","Fabrice","Fabricia","FabrÃ­cia","Fabricie","Fabricien","Fabricio","Fabricius","FabrÃ­ciusz",
            "Fabrizia","Fabrizio","Faddej","Fadej","Fanny","Fantino","Farran","Farren","Fatima","FÃ¡tima","Fauni","Faust","Fausta","Faustin","Faustina",
            "Faustina","Faustine","Faustino","Faustinus","Fausto","Faustus","Faustyn","FaustÃ½n","Faustyna","FaustÃ½na","Fausztina","Fausztusz","Favij","Favst","Favstina",
            "Fay","Faye","Feba","FÃ©ba","Febe","Febronia","Fedderik","Federica","Federico","Fedor","Fedora","FedÃ³ra","Fedosij","Felice","Felicia",
            "FelÃ­cia","Felician","FeliciÃ¡n","Feliciana","Felicie","FelÃ­cie","FÃ©licie","Felicija","Felicita","Felicitas","Felicity","Felicja","Felicjan","Felicjana","Feliks",
            "Feliksa","Felipa","Felipe","Felix","FÃ©lix","Felixa","Felizia","Felizitas","Fenella","Feodor","Feodora","Feodosij","Feodosija","Feofan","Feofil",
            "Feofila","Ferdenande","Ferdinand","FerdinÃ¡nd","Ferdinanda","Ferdinande","Ferdinando","Ferdynand","Ferdynanda","Ferenc","Fernand","Fernanda","Fernande","Fernando","Fidele",
            "Fidel","FidÃ©l","Fidela","Fidelia","FidÃ©lia","Fidelij","Fidelija","Fidelio","Fidelis","Fidelius","Fidelle","Filbert","Filberto","Filemon","FilemÃ³n",
            "Filemone","Filiberto","Filip","Filipa","Filipina","Filipina","Filipp","Filippa","Filippija","Filippo","Filippos","Filippus","Filomen","FilomÃ©n","Filomena",
            "FilomÃ©na","Filomeno","Fina","Finbar","Fine","Finella","Finette","Finn","Finna","Finne","Finni","Fiona","Fionn","Fionnuala","Fiva",
            "Fjodor","Fjokla","Flavia","FlÃ¡via","Flavian","FlaviÃ¡n","Flaviano","Flavie","Flavien","Flavij","Flavija","Flavio","Flavius","FlÃ¡vius","Flawia",
            "Flawian","Flawiusz","Fldelie","Fleur","Floortje","FlÃ³ra","Florance","Florence","Florencia","Florencij","Florencio","Florentia","Florentij","Florentin","FlorentÃ­n",
            "Florentina","FlorentÃ­na","Florentine","Florentino","Florentinus","Florentius","Florentyn","FlorentÃ½n","Florentyna","FlorentÃ½na","Floria","Florian","FloriÃ¡n","FlÃ³riÃ¡n","Floriana",
            "FloriÃ¡na","Floriano","Florianus","Florijan","Florin","Floyd","Fodor","Foma","Fomaida","Forest","Forrest","Fortunat","FortunÃ¡t","Fortunato","Fortunatus",
            "Fortunio","Fotini","Franca","Frances","Francesca","Francesco","Francine","Francis","Francisca","Francisco","Franciscus","Franciska","Francisque","Franciszek","Franciszka",
            "Franco","Francois","Francoise","Franjo","Frank","Franka","Franko","Frans","FrantiÅ¡ek","FrantiÅ¡ka","Franz","Franzine","Franziska","Franziskus","Fred",
            "Fredderik","Freddi","Freddy","Frederic","FrÃ©dÃ©ric","Frederica","Frederick","Fredericus","Frederik","Frederika","Frederikke","FrÃ©dÃ©rique","Fredrik","Fredrika","Fredrikke",
            "Freya","Frida","FrÃ­da","Friderika","Fridolin","FridolÃ­n","Fridolino","Fridrich","Frieda","Friederika","Friederike","Friedrich","Frigyes","Fritz","Frosyna",
            "Fryderik","Fryderyka","FÃ¼lÃ¶p","Gabi","Gabin","Gabina","GÃ¡bina","Gabinio","Gabino","Gabinus","GÃ¡bor","GabriÃ¤l","Gabriel","Gabriela","Gabriele",
            "Gabriele","Gabriella","Gabrielle","Gabriello","Gabrijel","Gabrina","Gaby","Gaea","GaÃ©tan","Gaetana","GaÃ©tane","Gaetano","Gaia","Gaius","Gaj",
            "Gaja","Gajana","GajÃ¡na","GajanÃ©","Gajanija","Gal","GÃ¡l","Gala","Galatea","GalatÃ©e","Galateia","Galatia","Galia","Galina","Gall",
            "Gallien","Gallo","Gallus","Galo","Galus","Ganna","Gareth","Garik","Garika","Garrick","Gary","Gaspar","GÃ¡spÃ¡r","Gaspard","Gaspare",
            "Gaston","Gastone","Gaszton","Gautier","Gavin","Gavriil","Gavril","Gavrilo","Gavrina","Gawel","Gayetano","Gedeon","GÃ©dÃ©on","Gedeone","Geertruda",
            "Geertrudis","Geertruida","Gejza","GellÃ©rt","Geltrude","Gema","Gemma","Genadij","Genadije","Genadio","Genciana","Genevieve","Geneviive","Gennadij","Gennadio",
            "Gennadius","Genovefa","GenovÃ©fa","Genoveffa","Genoveva","GenovÃ©va","Genoweffa","Genrietta","Genrich","Gentiane","Genziana","Geoffrey","Georg","Georga","George",
            "Georges","Georgette","Georgi","Georgia","Georgij","Georgija","Georgije","Georgina","Georgina","Georgine","Georgios","Georgius","Gerald","Geralda","Geralde",
            "GÃ©ralde","Geraldina","Geraldine","GÃ©raldine","Geraldo","Geraldus","Gerard","GÃ©rard","Gerarda","Gerardina","Gerardo","Gerardus","Gerasim","Geraszim","GÃ©raud",
            "Gerazim","Gerd","Gerda","Geremia","Gerga","Gergana","Gergely","Gergina","Gerhard","Gerharda","Gerharde","Gerhardina","Gerhardine","Gerlach","Gerlind",
            "Gerlinda","Gerlinde","Germaine","German","Gerold","Geronimo","Gerret","Gershom","Gershon","Gerson","Gert","Gerta","Gertie","Gertraud","Gertraude",
            "Gertrud","GertrÃºd","Gertruda","GertrÃºda","Gertrude","Gerwald","Geza","GÃ©za","Gheorge","Gheorghe","Ghita","Giacint","Giacinto","Giacobbe","Giacomo",
            "Giada","Gianni","Giannina","Gideon","Giko","Gil","Gilbert","Gilberta","Gilberte","Gilberto","Gilbertus","Giles","Gilles","Gina","Gine",
            "Gineta","Ginette","Ginglielmo","Ginlia","Gino","Ginseppa","Giobbe","Gioele","Giona","Gionata","Giordano","Giorgio","Giorgos","Giovanna","Giovanni",
            "Giralda","Girolamo","Gisbert","Gisela","Giselbert","Gisele","Gisella","Gita","Gitta","Gitte","Giuditta","Giuliana","Giuliano","Giulio","Giuseppe",
            "Giuseppina","Giustina","Giustino","Gizela","Gizella","Gjunter","Gladys","Gleb","Glen","Glenn","Gloria","Gloria","Glorie","Glorija","Glory",
            "Godard","Godardo","Godart","Goddard","Goddart","Goran","GÃ³ran","Gorana","Goranka","Gorazd","Gordana","Gordina","Gordon","Gorimira","Gortenzija",
            "Gosciwit","Gostimir","Gostimira","Gostislav","Gostislava","GoÅ¡cimir","GoÅ¡cislaw","Gotard","Gotardo","Gothard","GothÃ¡rd","Gottdank","Gottfried","Gotthard","Gottlieb",
            "Grace","GrÃ¡ce","Gracia","GrÃ¡cia","Gracian","GraciÃ¡n","Graciana","GraciÃ¡na","Graciane","Graciano","GrÃ¡cie","GrÃ¡cie","Graciela","Gracija","Gracija",
            "Gracijan","Gracja","Gracjan","Gracjana","Gradita","Grant","Gratia","Gratian","Gratianus","Grazia","Grazian","Graziano","Graziella","GraÅ¾ina","GraÅ¾yna",
            "Greger","GrÃ©goire","Gregor","Gregoria","GrÃ©goria","GrÃ©goriane","Gregorina","Gregorio","Gregorius","Gregoros","Gregory","Greta","GrÃ©ta","Grete","Gretha",
            "Grethe","Gretchen","Greti","Grigor","Grigore","Grigorena","Grigorij","Grigorija","Grigorina","Griseld","Griselda","Griseldis","Grizelda","Grizeldisz","Grozdan",
            "Gryzelda","Grzegorz","Gualterio","Gualterus","Gualtiero","Gubert","Gudrun","Guendalina","Guglielma","Guglielmina","Gui","Guido","Guilherme","Guillaume","Guillelmina",
            "Guillelmine","Guillermo","Guinevere","GujdÃ³","Gulliver","Gunar","Gunnar","Gunter","Gunter","Guntero","Gunther","Gun?her","Guntherus","Guntrun","Gustaaf",
            "Gustaf","Gustav","Gustav","Gustava","Gustava","Gustave","Gustavo","Gustavus","Gustaw","Gustawa","Gustina","GustÃ­na","GustÃ½na","GusztÃ¡v","Guy",
            "Gvenda","Gvendolina","GvendolÃ­na","Gvido","Gweanel","Gwen","Gwenda","Gwendolen","Gwendolin","Gwendoline","Gwendolyn","Gwido","Gwidon","Gyorgy","GyÃ³zo",
            "Gyula","Hadewig","HadriÃ¡n","Hadriana","Hadrianna","Hagar","Haide","Haidi","Haidrun","Hajnal","Hajnalka","Halija","Halina","Halka","Halyna",
            "Hamilton","Hamis","Hana","Hanele","Hanelora","Hanelore","Hanerosa","Hanka","Hanna","Hannah","Hanne","Hannele","Hannelore","Hannerose","Hanni",
            "Hans","HanuÅ¡","HanuÅ¡e","HanuÅ¡ka","Harald","Harbert","Hardi","Hardy","Harieta","Harley","Harold","Harriet","Harry","Harun","HaÅ¡tal",
            "HÃ¡ta","Havard","Havel","Havla","Hector","Heda","Hedda","Hedvig","Hedviga","Hedviges","Hedvika","Hedwig","Hedwige","Heidelinde","Heidemarie",
            "Heidi","Heidrun","Heike","Heike","Heiko","Heimeran","Heinrich","Heinz","Hektor","Helen","HelÃ©n","Helena","Heleni","HÃ©lene","Helga",
            "Heliodor","Hellmuth","Helmut","Helmuth","Heloise","HÃ©loise","Hendrik","Hendrika","Hendrike","Henni","Henny","Henri","Henricius","Henricus","Henrieta",
            "Henrietta","Henriette","Henrich","Henrijeta","Henrik","Henrika","Henrike","Henrique","Henriqueta","Henry","Henryk","Henryka","HÃ©raud","Herbert","Herberta",
            "Herbertine","Herberto","Heribert","Heriet","Herieta","Herma","Herma","Herman","Herman","Hermaun","Hermina","Hermina","HermÃ­na","Hermini","Herminia",
            "Hernando","Herta","Hertha","Heoman","Heomana","HeomÃ¡nka","Hiacynt","Hieronim","Hieronimo","Hieronimus","Hieronym","Hieronymus","Hilaire","Hilar","HilÃ¡r",
            "Hilaria","HilÃ¡ria","Hilarij","Hilario","Hilarius","HilÃ¡rius","HilÃ¡riusz","Hilary","Hilary","Hilda","Hildi","Hillary","Hillary","HilmÃ¡r","Hiob",
            "Hipolit","Hipolito","Hippolit","Hippolite","Hippolitus","Hippolytus","Hjalmar","Homer","Homer","HomÃ©r","Homire","Homerus","Honey","Honor","Honorata",
            "HonorÃ¡ta","HonorÃ©","Honoria","Honorij","Honorina","Honorine","Honorius","HonÃ³riusz","Honory","HorÃ¡c","Horace","Horacij","Horacio","Horacjusz","Horacy",
            "Horatio","Horatius","Horst","Hortense","Hortensia","Hortensie","Hortensija","Hortensja","Hortenzia","Hortenzie","HorymÃ­ra","Horymrr","Hooislava","Hostimil","Hostimila",
            "HostimÃ­r","HostimÃ­ra","Hostislav","Hostislava","HostivÃ­t","Hovard","Howard","Hrabra","Hrabri","Hranisav","Hranislav","Hranislava","HroznatÃ¡","Hubert","Huberta",
            "Huberto","Hubertus","Hubrecht","Hugbert","Hugh","Hugo","Hugo","Hugohn","Hugon","Hugue","Hugues","Humbert","Hvalenko","Hvizdo","Hvezdoo",
            "Hvizdoslava","Hviezdoslav","Hviezdoslava","Hyacint","Hyacinta","Hyacinte","Hyacinth","Hyacintha","Hyacinthe","Hyacinthe","Hyacinthus","Hyazint","Hyazinth","Hyazintha","Hyazinthus",
            "Hynek","Hypolit","Chadwick","Chaim","Chaja","Chanel","Chantal","Chantalle","Charalambos","Charilaos","Charline","Charles","Charlette","Charlie","Charlie",
            "Charlota","Charlotta","Charlotti","Chaya","Chelsea","Cheryl","Chiara","Chimalli","Chloe","ChloÃ©","Chrabr","Chrabro","ChrabroÅ¡","Chraniboj","Chranibor",
            "Chranimir","Chranislav","Chranislava","ChrÃ©tien","ChrÃ©tienne","Chris","Chris","Chris","Christa","Christakis","Christalina","Christel","Christiaan","Christian","Christiana",
            "Christiane","Christianus","Christie","Christie","Christien","Christin","Christina","Christine","Christo","Christoffer","Christofor","Christoph","Christophe","Christopher","Christopherus",
            "Christos","ChrudoÅ¡","Chrystian","Chrystja","Chval","Chvalislav","Iain","Iakim","Iballa","Iboja","Ibolja","Ibolya","Ibrahim","Ida","Idaberga",
            "Ide","Idzi","Ieron","Ieronim","IgnÃ¡c","IgnÃ¡c","IgnÃ¡ce","IgnÃ¡cia","IgnÃ¡cie","Ignacij","Ignacio","Ignacja","Ignacy","Ignat","IgnÃ¡t",
            "IgnÃ¡ta","Ignatia","Ignatij","Ignatius","Ignaz","Ignazio","Ignez","Igor","Iisus","Ika","Iker","Ikerne","Ilarij","Ilario","Ilarion",
            "Ildefonso","Ildico","Ildika","Ildiko","IldikÃ³","Ileana","Ilian","Iliana","Ilias","Ilija","Ilija","Ilijana","Ilike","Ilja","Ilja",
            "Iljana","Iljina","IllÃ©s","Illja","Ilona","Ilonka","Ilsa","Ilza","Ima","Imanuil","Imelda","Imma","Immanuel","Immanuela","Immanuil",
            "Imre","Imrich","Ince","Ines","InÃ©s","Inis","Inesa","Inessa","Inez","InÃ©z","Inga","Inge","Ingeborg","Ingeborga","Ingrid",
            "Ingrida","Ingryda","Ingvar","Ingwar","Inigo","Ioigo","Inka","Inken","Inna","Innes","Innocent","Innocentius","Innocenty","Innokentij","Innozenz",
            "Inocenc","Inocencio","Inocent","Inocentius","Inocenzo","Inoeent","Inokentij","Inokentije","Ioakim","Ioan","Ioann","Ioanna","Ioannes","Ioannis","Ioil",
            "Iolanthe","Iona","Ionas","Iordan","Iosif","Ioulia","Ippolit","Ira","Ira","Iraida","Iren","Irena","Irena","IrenÃ¡us","Ireni",
            "Ireni","IrÃ©nÃ©","Irine","IrÃ©nÃ©e","IrÃ©nÃ©e","Ireneo","Ireneus","Ireneusz","Irijan","Irin","Irina","Irineu","Irinij","Iris","Ã­risz",
            "Irma","Irme","Irmina","Irvin","Irvine","Irving","Irwin","Isa","Isaac","Isaak","Isaakij","Isabel","Isabela","Isabella","Isabelle",
            "Isacco","Isadora","Isaia","Isaiah","Isaias","Isaja","Isbel","Isidoor","Isidor","Isidora","Isidore","Isidoro","Isidorus","Isis","Iskandar",
            "Ismaele","Isobel","Isolda","Isolde","Israel","IstvÃ¡n","Iuda","Iuliain","Iustini","Iva","Ivain","Ivajlo","Ivan","IvÃ¡n","Ivana",
            "Ivana","Ivanka","Ivar","Ivauna","Iver","IvÃ©s","Iveta","Ivetta","Ivette","Ivica","Ivka","Ivo","IvÃ³","Ivona","Ivoni",
            "Ivonn","Ivonne","Ivor","IvoÅ¡","Iwa","Iwan","Iwana","Iwo","Iwona","Izaak","Izabel","Izabela","Izabell","Izabella","IzaiÃ¡s",
            "IzaiÃ¡Å¡","Izaija","Izajasz","IzÃ¡k","IzÃ¡k","Izidor","Izidora","IzidÃ³ra","Izmael","Izmail","Izolda","IzsÃ¡k","Izydor","Izydora","Jaakob",
            "Jacek","Jacenty","Jacinto","Jack","Jacob","Jacoba","Jacobina","Jacobine","Jacobo","Jacopo","Jacquelina","Jacqueline","Jacquelyn","Jacques","Jade",
            "Jadon","Jadrana","Jadranka","Jadviga","Jadwiga","Jadyn","Jago","JahjÃ¡","JÃ¡chym","Jaime","Jakab","Jake","Jakim","Jakiv","Jakob",
            "JÃ¡kob","Jakoba","Jakobe","Jakobina","Jakobine","Jakov","Jakovos","Jakub","Jakuba","Jakubka","Jakup","Jalmari","Jamaica","James","Jamie",
            "Jamin","Jan","JÃ¡n","Jana","Jane","Janek","Janella","Janelle","Janet","Janetta","Janette","Janica","Janice","Janick","Janika",
            "Janina","Janis","Janka","Janne","Jannick","Jannik","Jannis","JanoÅ¡","JÃ¡noÅ¡","Jans","Jantra","Janusz","Jar","Jara","Jarema",
            "Jari","Jarina","Jarmil","Jarmila","Jarmilo","JarolÃ­ma","Jaromil","Jaromila","Jaromila","JaromÃ­r","JaromÃ­r","JaromÃ­ra","Jaromirka","Jarosav","Jaroslav",
            "Jaroslava","Jaroslaw","Jaroslaw","Jaroslawa","Jarounra","JaruÅ¡e","Jas","Jasan","Jasana","Jasen","Jasenka","Jasmin","Jasmina","JasmÃ­na","JasmÃ­ne",
            "Jasna","Jasna","Jasnina","Jason","Jasoo","JasÃ³n","Jasper","Javier","Jayme","Jayne","JÃ¡zmin","Jazmina","Jean","Jean","Jeanette",
            "Jeanne","Jeannette","Jeannie","Jeannine","Jed","Jedidiah","Jefferson","Jeffrey","Jeffry","Jefim","Jefrem","Jefrosinija","Jefrosinja","Jegor","Jekaterina",
            "Jela","Jeleazar","Jelena","Jelisaveta","Jelisej","Jelizar","Jelizaveta","Jemeljan","Jenica","Jenifer","Jenny","JenÃ³","Jenovefa","JenovÃ©fa","Jens",
            "Jentl","Jeorjia","Jeremej","Jeremi","Jeremia","Jeremiah","Jeremiasz","JeremiÃ¡Å¡","JeremiÃ¡Å¡","JeremiÃ¡Å¡","JeremiÃ¡Å¡","JÃ©rÃ©mie","Jeremija","Jeremy","JerguÅ¡",
            "Jerome","JÃ©rome","Jeromos","Jeronim","Jeronimo","JerÃ³nimo","JeronÃ½m","JeronÃ½m","Jerry","Jerzy","Jesika","Jessamine","Jesse","Jessica","Jessie",
            "Jessika","Jeunifer","Jeva","Jevdokija","Jevgen","Jevgenij","Jevgenoja","Jevlalija","Jevnika","Jevnikija","Jevsevija","Jezekija","Jil","JiljÃ­","Jill",
            "Jilliana","Jim","Jimmy","Jimram","Jindra","Jindra","Jindoich","JindoiÅ¡ka","Jinke","Jinke","JioÃ­","Jioina","Jitka","Joachim","Joakim",
            "Joanico","Joanis","Joann","Joanna","Joannis","Joannus","JoÃ¡o","Joaqinm","JoaquÃ­n","Job","JÃ³b","Jocelyna","Jocelyne","Jodie","Jodocus",
            "Jodokus","Jody","Joel","Joelle","Johan","Johana","Johanka","Johann","Johanna","Johannus","Johaunes","John","Johnny","Johnson","Jola",
            "Jolan","Jolana","Jolanda","Jolanta","Jolante","Jolantha","Jolanthe","Jolie","Jolla","Jon","Jona","Jonah","Jonas","JÃ³nÃ¡s","Jonasz",
            "JonÃ¡Å¡","JonÃ¡Å¡","Jonatan","JonatÃ¡n","Jonathan","JordÃ¡n","JordÃ¡na","JordÃ¡na","Jordanka","Jordanus","Jorga","Jorge","JÃ³rgen","Jorgina","Jorgos",
            "Jori","Jorik","Jorika","Joriko","Joris","Jorjia","JÃ³rn","JosÃ©","Josef","Josefa","Josefina","JosefÃ­na","Josefine","Joseph","Josepha",
            "Josephina","Josephine","JosÃ©phine","Josephus","Joshua","Joschua","Josif","Josifa","Josip","Josipa","Josse","Jost","Josua","JosuÃ©","JoÅ¡t",
            "Jovan","Jovana","Jovanka","Joy","Joyce","Joyce","Jozef","JÃ³zef","Jozefa","JÃ³zefa","Jozefina","Jozefina","Jozefina","Jozephina","JÃ³zsef",
            "JÃ³zsua","Jozua","Jozue","Jorgen","Juan","Juana","Juda","Juda","Judah","JudÃ¡Å¡","Judd","Judif","Judit","Judita","Judith",
            "Judy","Judyta","Jule","Jules","Julia","Julia","Juliaan","Julian","JuliÃ¡n","Juliana","JuliÃ¡na","Juliane","Julianija","Julianna","Juliano",
            "Julianus","JuliÃ¡nusz","Julie","Julien","Julienne","Juliet","Juliette","Julij","Julij","Julijan","Julijana","Julio","Julius","Julius","Juliusz",
            "Juloja","Julyan","Julyna","Jura","Juraj","Juraja","JurÃ¡Å¡","JÃºrgen","Jurij","Justian","JustiÃ¡n","Justin","Justin","Justina","Justina",
            "Justina","Justine","Justinian","JustiniÃ¡n","Justinianus","Justino","Justinus","Justus","JustÃ½n","JustÃ½n","JustÃ½na","JustÃ½na","Jusuf","Jusztin","Jusztina",
            "Juta","Jutka","Jutta","Jutte","Juzef","Juzefa","Kaelin","Kaelyn","Kai","Kai","Kaila","Kain","Kaina","Kaitrin","Kaj",
            "Kaj","KajetÃ¡n","KajetÃ¡n","KajetÃ¡na","KajetÃ¡na","Kajna","Kaliman","Kalina","KalipszÃ³","KÃ¡lmÃ¡n","Kalypso","Kameron","Kamil","Kamila","Kamill",
            "Java","Konstanse","Konstantin","Konstantin","Konstantina","Konstantina","Konstantine","Konstantinos","Konstanty","Konstantyn","KonstantÃ½n","KonstantÃ½na","Konstanze","Konstjantyn","Konsuela","Konzuela",
            "Kora","Kordelia","KordÃ©lia","Kordula","Korina","Korinna","Kornel","Kornel","Korneli","Kornelia","KornÃ©lia","Kornelie","KornÃ©lie","Kornelij","Kornelija",
            "Kornelius","Korneliusz","Kornilij","Koryna","Korynna","Kosma","Kosmas","Kostadin","Kostandin","Kostantin","Kozma","Kozmas","KrÃ¡sa","Krasava","Krasena",
            "Krasimir","KrasimÃ­r","Krasimira","Krasislav","KrÃ¡sna","KrÃ¡sno","Krasnoj","Krasnomir","Krasnomira","Krasomil","Krasomila","KrasomÃ­ra","Krasoslav","Krasoslava","Krescencia",
            "Krescencie","Kreszcencia","KreÅ¡imir","Krispin","Krispus","Krista","Kristen","Kristen","Kristi","KristiÃ¡n","KristiÃ¡n","KristiÃ¡na","KristiÃ¡na","Kristijan","Kristin",
            "Kristina","Kristina","Kristini","Kristof","Kristof","KristÃ³f","Kristofer","Kristoffer","Kristy","KristÃ½na","KrisztiÃ¡n","Krisztina","KriÅ¡pin","Krstina","Kryspin",
            "Krystian","Krystiana","Krystyn","Krystyna","KryÅ¡pÃ­n","KryÅ¡tof","Krzesimir","Krzysztof","Koesomysl","KoiÅ¡?an","KoiÅ¡?ana","Ksaverij","Ksaverije","Ksawera","Ksawery",
            "Ksenia","Ksenija","Kunegunda","Kunhuta","Kunigonde","Kunigunda","Kunigunde","Kuprijan","Kurt","Kuzma","Kventin","Kvita","KvÃ©tanÃ¡","Kvetava","Kvitomil",
            "Kvitomila","KvitomÃ­r","Kvetoo","Kvitoo","Kvitoslav","Kvitoslav","Kvitoslava","Kvitoslava","KvitoÅ¡","KvituÅ¡e","Kvido","Kvinton","Kvirin","Kvirin","KÃ½la",
            "KÃ½le","KÃ½le","Kyriak","Kyriaki","Kyrill","Kyrillus","Kyrillus","Lada","Ladana","Ladina","LadimÃ­ra","Ladislao","Ladislas","Ladislau","Ladislaus",
            "Ladislav","Ladislava","Ladiszla","Laika","LadomÃ©r","Laetitia","Laila","Lajla","Lajos","Lambert","Lamberto","Lambrini","Lamprecht","lan","Lana",
            "Lara","Larina","Larisa","Larissa","Lars","Larysa","LÃ¡szlÃ³","LÃ¡titia","Laur","Laura","Laure","Lauren","Laurenc","Laurence","Laurence",
            "Laurencia","Laurencie","Laurencij","Laurencije","Laurencio","Laurencja","Laurencjusz","Laurens","Laurent","Laurentia","Laurentin","Laurentin","Laurentino","Laurentius","Laurenty",
            "LaurentÃ½n","Laurenz","Laurette","Laurids","Laurie","Laurits","Laurus","Lavra","Lavrentij","Lavrentije","Lavrin","Lavro","Lawrence","Layla","Lazar",
            "Lazar","LÃ¡zÃ¡r","Lazare","LÃ¡zaro","Lazaros","Lazarus","Lazarz","Lazzaro","Lea","LÃ©a","Leah","Leandar","Leandr","Leandra","LÃ©andre",
            "Leandro","Leandru","Leda","Leda","Lee","Lee","Leila","Leilah","Leilani","Leja","Lejla","Len","Lena","LÃ©na","Lene",
            "Lenek","Leni","Lenica","Lenka","Lenke","Lenko","Lennart","Lenny","Lenta","Leo","LeÃ³","Leocadia","LÃ©ocadie","Leodegar","Leodegario",
            "Leokadia","LeokÃ¡dia","Leokadie","LeokÃ¡die","Leokadija","Leon","Leon","Leon","Leona","Leona","Leonard","Leonard","LÃ©onard","Leonarda","Leonardo",
            "LÃ©once","Leoni","LÃ©one","Leonela","Leonella","Leoneta","Leonetta","Leonhard","Leonia","Leonid","Leonidas","LeonÃ­das","LeonidÃ¡sz","LeÃ³nides","Leonie",
            "LÃ©onie","Leonija","Leonila","Leonor","Leonora","Leontij","Leontija","Leontije","Leontin","LeontÃ­n","Leontina","Leontina","Leontine","LÃ©ontine","Leontinus",
            "Leontyn","LeontÃ½n","Leontyna","LeontÃ½na","Leopold","Leopold","Leopolda","Leopoldina","Leopoldina","Leopoldine","Leopoldo","Leopoldus","Leopoldyna","LeopoldÃ½na","LeoÅ¡",
            "Lesana","Lesbia","Leschek","Leszek","LeÅ¡ek","Leta","Lethea","Lethia","Letia","Leticia","LetÃ­cia","Leticie","Leticija","Letitia","Letizia",
            "Letta","Letycja","Lev","Levi","Lew","Lewis","Leyla","Lia","LÃ­a","Liam","LiÃ¡na","LiÃ¡na","Liane","Lianna","Lianne",
            "Libina","Liberta","Libislava","Libor","Libora","Liborio","Liborius","Liboslav","Liboslava","Libussa","Libusza","LibuÅ¡a","LibuÅ¡e","Lida","LÃ­da",
            "Lidia","LÃ­dia","Lidija","Lidmila","Liesa","Liese","LÃ­f","LÃ­hÃ¡na","Lij","Lijana","Lil","Lili","Lili","Lilia","Lilia",
            "Lilia","Lilian","Liliana","Liliane","Lilien","Lilii","Lilija","Lilijana","Lilith","Lilja","Liljan","Liljana","Lillian","Lilly","Lilo",
            "Lilou","Lily","Lina","Linda","Lindi","Lindsay","Lindsey","Line","Lingi","Lino","Lins","Linsbel","Linse","Linton","Linus",
            "Lion","Lionardo","Lionel","Lionello","Lior","Liora","Liran","Lirid","Lirida","Liridon","Liron","Lisa","Lisbet","Lise","Lissa",
            "Lisse","Lita","Litka","Liv","Livia","Livij","Livija","Livije","Livio","Liviusz","Liwia","Liwiusz","Liz","Liza","Ljuba",
            "Ljubana","Ljuben","Ljubica","Ljubim","Ljubina","Ljubislava","Ljubomir","Ljubomira","Ljubomyla","Ljubomyra","Ljuboslav","Ljuboslava","Ljubov","LjubuÅ¡a","Ljucian",
            "Ljucija","Ljudevit","Ljudevita","LjudiÅ¡a","Ljudmil","Ljudmila","Ljudvig","LMa","LMe","LMo","LMus","LMus","lna","Lodevika","Lodewijk",
            "Lodovica","Lodovico","Lodowick","Loic","Loins","Lois","Lois","Lois","Loise","Lola","Lolita","Lona","Lone","Longin","Longino",
            "Loni","Lora","Loraine","LÃ³rÃ¡nt","Lore","Loreen","Loren","Lorena","Lorenc","Lorenz","Lorenzo","Loreta","Loretta","Lori","Lorina",
            "LÃ³rinc","LÃ³rinc","Lorna","Lorne","Lorraine","Lota","Lotar","LotÃ¡r","Lotario","LotariÃºs","Lothaire","Lothar","Lotharius","Lotta","Lotte",
            "Lou","Lou","Louisa","Louise","Loukia","Loup","Luba","Lubina","Lubica","Lubica","Lubislava","Lubomil","Lubomila","LubomÃ­r","LubomÃ­r",
            "LubomÃ­r","LubomÃ­ra","LubomÃ­ra","LubomÃ­ra","Lubor","Lubor","Lubor","Lubora","Luboslav","Luboslav","Luboslava","Luboslava","Luboslaw","LuboÅ¡","LuboÅ¡",
            "Lubov","Luc","Luca","Lucas","Lucia","LucÃ­a","LÃºcia","Lucian","LuciÃ¡n","Luciana","LuciÃ¡na","Lucianna","Luciano","Lucianus","LucibeU",
            "Lucie","Lucien","Lucieune","Lucija","Lucijan","Lucilla","Lucio","Lucius","LÃºciusz","Lucja","Lucjana","Lucrece","Lucrice","Lucrecia","Lucrecio",
            "Lucretia","Lucretiu","Lucretius","Lucrezia","Lucrezio","Lucy","Lueina","Ludik","Ludina","LudevÃ­t","Ludimir","LudimÃ­r","Ludislav","LudiÅ¡e","Ludivoj",
            "Ludka","Ludmil","Ludmila","Ludmila","Ludmila","Ludmilla","Ludomila","Ludomir","Ludomir","LudomÃ­r","Ludomira","Ludomira","LudomÃ­ra","Ludoslav","Ludoslav",
            "Ludoslava","Ludoslava","Ludoslaw","Ludoslawa","Ludovica","Ludovicus","Ludovika","LudovÃ­t","LudovÃ­ta","Ludowic","Ludowick","Ludvig","Ludviga","LudvÃ­k","Ludvika",
            "LudvÃ­ka","Ludwig","Ludwiga","Ludwik","Ludwika","Luigia","Luigino","Luisa","Luitpold","Luiz","Luiza","Lujza","Luka","Luka","LukÃ¡cs",
            "Lukan","Lukana","Lukas","Lukasz","LukÃ¡Å¡","LukÃ¡Å¡ka","Luke","Lukia","Lukija","Lukina","Lukrecia","LukrÃ©cia","Lukrecie","LukrÃ©cie","Lukrecij",
            "Lukrecija","Lukrecius","Lukrecja","Lukrecjusz","Lukretia","LumÃ­r","LumÃ­ra","Luna","Lune","Lusibell","Lusine","Luther","Lutherus","Lutibor","Lutobor",
            "Luzia","LuzÃ­a","Lydia","LÃ½dia","Lydie","LÃ½die","Lynda","Lynete","Lynn","Lynnette","Mabel","Mabela","Mabelia","Mabella","Mabelle",
            "Mable","Mac","Macaire","Macario","Macarius","Maciej","Mackenzie","MacKenzie","Madalena","Maddalena","Maddison","Maddison","Madeleine","Madeline","Madison",
            "Madison","Madleen","Madlen","Madlena","Madonna","Madrona","Madrun","Maeve","Magda","Magdala","Magdalena","MagdalÃ©na","Magdaleni","Magdalina","Magdalini",
            "Magdolna","Maggie","Magia","Magn","Magne","Magno","Magnus","Magnusz","Mahulena","Mahuliena","Macharius","Mai","Maia","Maible","Maik",
            "Maikel","Mailin","Maina","Maire","Maj","MÃ¡ja","MÃ¡ja","Majja","Majka","Makar","MakÃ¡r","Makarij","Makarije","Makarius","Makariusz",
            "Makary","Makeda","Maksim","Maksima","Maksimian","Maksimilian","Maksimilijan","Maksimiljan","Maksym","Maksymilian","Malena","Malgorzata","Mali","Malin","Mallory",
            "Mallory","Malva","MalvÃ­n","MalvÃ­na","MalvÃ­na","Malvy","Malwina","Malwine","Mandy","Manfred","ManfrÃ©d","Manfredi","Manfredo","Manfried","Manfroy",
            "Manka","Manogu","Manoila","Manol","Manon","Manona","Mansueto","Mansuetus","Mansvet","MansvÃ©t","ManszvÃ©t","Manuel","Manuela","ManuÃ©la","Manuele",
            "Manuelle","Manuil","Manus","Mara","Marat","Marc","Marcel","Marcela","Marceli","Marceli","Marcelia","Marcelia","Marcelija","Marcelin","Marcelin",
            "Marcelina","MarcelÃ­na","Marcelle","Marcellina","Marcello","Marcellus","Marcelo","Marcia","Marcin","Marco","Marcos","Marcu","Marcus","Mareike","Marek",
            "Marfa","Marga","Margaret","Margareta","Margareta","Margareti","Margaretha","Margarethe","Margaretta","Margarita","Margherita","Margit","Margita","Margitha","Margitta",
            "Margot","Margre?he","Marguerite","Maria","Maria","Mariamna","Marian","MariÃ¡n","Mariana","Marianna","Marianne","Mariano","Marianus","Maribel","Marica",
            "Maricela","Marie","Mariel","Mariela","Mariella","Marielle","Marien","Marieta","Marietta","Mariette","Marij","Marija","Marijan","Marijana","Marika",
            "Marilla","Marilyn","Marilyne","Marilynn","Marin","Marina","Marina","Marini","Marino","Marinus","Mario","Mario","Mariola","Mariole","Marion",
            "Mariona","Marisa","Marisela","Mariska","MariÅ¡a","Marita","Maritta","Marius","MÃ¡rius","Mariusz","MÃ¡riusz","Marjana","Marjo","Marjorie","Marjory",
            "Mark","MÃ¡rk","Markel","Markell","Markellina","Markelo","MarkÃ©ta","Marko","Markos","Markus","MÃ¡rkus","Marleen","Marlen","Marlena","Marlene",
            "Marlene","MarlÃ©ne","Marlon","Maro","Maron","MaroÅ¡","Marquita","Marro","Marta","Marta","Marten","Martha","Marthe","Martin","Martina",
            "Martina","Martine","Martinian","MartiniÃ¡n","Martiniano","Martinka","Martino","Martjan","MÃ¡rton","Marty","Martyn","Martyna","MaruÅ¡e","Marvin","Mary",
            "Maryla","Maryna","MaryÅ¡a","Marzella","Marzellus","Maoen","MaoÃ­","Maoila","Masa","Masha","Mascha","Massimiliano","Massimo","MaÅ¡a","MÃ¡Å¡a",
            "MaÅ¡enka","MÃ¡tÃ©","Matea","Matei","Matij","Matij","Matij","Matij","Matij","Matijka","Matelda","Mateo","Mateusz","Matfij","Mathea",
            "Mathias","Mathie","Mathies","Mathieu","Mathilda","Mathilde","Mathis","Matias","MatÃ­as","MatiÃ¡Å¡","Matij","Matija","Matija","Matild","Matilda",
            "Matilde","Mato","MatouÅ¡","Matt","Mattea","Matteo","Matthaeus","Matthaus","Matthew","Matthias","Matthieu","Matti","Mattia","Mattias","Mattis",
            "Matts","MatÃºÅ¡","Matvej","Matvij","Matyas","MatyÃ¡Å¡","MatyÃ¡Å¡","MatyÃ¡Å¡ka","Matylda","Maud","Maude","Maudie","Maura","Maurice","Mauricio",
            "Mauriciu","Mauricius","MaurÃ­cius","Mauritius","Maurits","Mauritz","Maurizio","Mauro","Maurycjusz","Maurycy","Mavrikij","Max","MaxiÃ¡n","Maxie","Maxim",
            "Maxima","Maxima","Maxime","Maxime","Maximiliaan","Maximilian","MaximiliÃ¡n","Maximiliana","Maximiliane","Maximiliano","Maximilien","Maximilla","Maximo","Maxine","Maxmilian",
            "MaxmiliÃ¡n","MaxmiliÃ¡na","MaxmiliÃ¡na","Maxwell","May","Maya","Mca","Mckenzie","McKenzie","Meeislav","Meeislava","Meda","Medard","Medard","Medard",
            "Medardo","Medardus","MÃ©dea","MÃ©dea","Mefodij","Meg","Megan","Meggi","Meggie","Meggy","Meghan","Mechthild","Mechtild","Mechtilda","Mechtilde",
            "Melana","MelÃ¡nia","Melanie","MelÃ¡nie","MÃ©lanie","Melanija","Melany","Melchior","Melchiorre","Melchor","Melichar","Melina","Melinda","MÃ©linda","Meline",
            "Melisa","Melissa","MÃ©lisse","Melita","Melitta","Melodie","Melody","Melony","Melpomeni","Melvffle","Melvin","Melvina","Menahem","Menachem","Mendel",
            "MenyhÃ©rt","Mercedes","Mercedes","MercÃ©desz","Merit","Merita","Merlijn","Merlin","Merlinus","Mersija","Mervin","Mervyn","Mesmin","MiÅ¡ek","Meta",
            "Methodius","Metod","Metod","Metodij","Metodi","Metodij","Metodije","Metodio","Metodiu","Metodius","Metody","Metta","Mette","Mia","Micaela",
            "Micislao","Mick","Mickey","Micky","Mieiko","Miecislao","Miecislas","Miecislav","Mieczyslaw","Mieczyslawa","Mieszko","Miguel","Miguela","MihaÃ©la","Mihai",
            "Micha","Michael","Michaela","Michaela","Michail","Michaila","Michajlina","Michajlo","Michal","Michal","Michala","Michalina","Michalis","Michel","Michela",
            "Michele","Michile","Michelina","Michelle","Michiko","Mija","Mika","Mikael","Mikaela","Mike","MikeÅ¡","Mikiko","Mikki","MiklÃ³s","Mikola",
            "Mikolaj","Mikolaj","MikolÃ¡Å¡","MikulÃ¡Å¡","Mila","Milada","Miladina","Milan","MilÃ¡n","Milana","Mileo","Mildred","Milen","Milena","Milena",
            "Mileni","Mileva","Milic","Milica","MilÃ­e","Milij","MilÃ­k","Milika","MilÃ­n","Milina","Milivoj","Milivoje","Miljan","Miljana","MiljuÅ¡a",
            "Miljutin","Milka","Milko","Milli","Milo","Miloje","Milojko","MilomÃ­ra","Miloo","Milorad","Milorad","Miloslav","Miloslava","Miloslaw","Miloslaw",
            "Miloslawa","Miloslawa","Milosz","MiloÅ¡","MiloÅ¡","Milota","Milota","Milotija","MilouÅ¡","MilovÃ¡n","MilovanÃ¡","MilovÃ­n","Milowan","Milton","MiluÅ¡a",
            "MiluÅ¡e","Milutin","Milutin","Mimi","Mimmi","Mimosa","Mina","MÃ­na","Minail","Minajlo","MinÃ¡ly","Mine","Mine","Minerva","Minka",
            "Minna","Minnie","Mir","Mira","MÃ­ra","Mirabel","Mirabela","Mirabella","Mirabelle","MirabeU","Miran","Miranda","Mirandola","Mireo","Mireille",
            "Mirek","Mirela","Mirella","Miriam","Miriama","Miriamna","Miriel","Miriela","Mirina","Mirjam","Mirjana","Mirka","Mirko","Mirko","Mirna",
            "Miroljub","Miroljuba","Miromil","Miromila","Miron","MirÃ³n","Miroslaus","Miroslav","Miroslava","Miroslavo","Miroslaw","Miroslaw","Miroslawa","Miroslawa","Mirtil",
            "Mirtill","Mirtilo","MÃ­rumila","Misha","MiÅ¡ela","Mitchell","Mitko","Mito","Mlad","Mlada","Mladan","Mladin","Mladina","MladotÃ­n","Mnata",
            "Mni","Mnislav","Mnislava","Moana","Modest","Modesta","Modeste","Modeste","Modestia","Modestina","Modesto","Modestus","ModestÃ½na","Modeszta","Modesztusz",
            "Modron","Moinque","Moira","Moise","Moisej","Moises","MoisÃ©s","Mojmir","MojmÃ­r","MojmÃ­ra","MojmÃ­ra","Mojsej","Mojsij","Mojsija","Mojsije",
            "Mojzesz","MojÅ¾Ã­Å¡","Momir","Momira","Mona","Monica","MÃ³nica","Monika","Monika","Montana","Monte","Montgomery","Monty","MÃ³r","Morgan",
            "Morgan","Morgana","Morganne","Moric","Moric","Moris","Moritz","Moriz","Morna","Morris","Morten","Mortimer","Morton","Mooena","Mooic",
            "Mose","Moses","Moshe","MoUy","Moyra","Moyse","Moyses","Mozes","MÃ³zes","Mstibor","Mstislaus","Mstislav","Mstislava","Mstivoj","MÅ¡cislaw",
            "Mudroslava","Muireall","Muriel","Muriela","Murielle","Musa","Mychajlina","Mychajlo","Mylana","Myloslava","Mylycja","Myriam","Myrna","Myron","Myroslava",
            "Myrta","Myrtea","Myrtha","Myrthe","Myrtil","Myrtille","Myrto","Myslibor","MyÅ¡libor","Naia","NadÃ¡n","Nadije","Nadeschda","NadiÅ¾da","NadiÅ¾da",
            "Nadia","Nadija","Nadine","Nadinka","Nadja","NÃ¡dja","Nadjeschda","Nadzieja","Naila","Naille","Nafanail","Naike","Nancy","NÃ¡ndor","Naneta",
            "Nanetta","Nanette","Nannette","Nansi","Naomi","Napoleon","Napoleon","Napoleon","Napoleon","Napoleone","Narcis","Narcis","Narcisa","Narciso","Narcissa",
            "Narcisse","Narcisse","Narcisso","Narcissus","Narcisszusz","NÃ¡rcisz","Narcyz","Narcyza","Narek","Narkiss","Narkissa","Nas?a","Nastasia","Nastasija","Nasti",
            "Natacha","Natali","Natalia","NatÃ¡lia","NatÃ¡lie","NatÃ¡lie","Natalija","Natalja","Natan","NÃ¡tÃ¡n","Natanael","Natanaela","Nataniel","Nataniela","Nataniele",
            "Natasha","Natascha","NataÅ¡a","NataÅ¡a","Nathalia","Nathalie","Nathaly","Nathan","Nathanael","Nathanail","Nathanaela","Nathanaille","Nathaniel","Nathaniela","Nazar",
            "Nazareno","Nazarij","Nea","Neal","Ned","Neda","Nedda","Neela","Neele","NefelÃ©","Nefely","Negislav","Negosav","Negoslav","Nehoslav",
            "Nihoslav","Neil","Neklao","Nela","Neli","Nelia","Nelie","Nelja","Nell","Nella","Nelli","Nellie","Nelly","Nelson","Nemanja",
            "Nena","Nenad","Nenah","Nenela","Nenella","Nennela","Nennele","Nepomuceno","Nepomuk","Neris","Nerys","Nesta","Nestir","Nestor","Neta",
            "Netta","Nette","Neunella","Neven","Nevena","Nevenka","Nezamysl","Nia","Niamh","Niccolo","Nice","Nicea","Niceta","Nicia","Nick",
            "Nicki","Nicki","Nicky","Nicky","Nico","Nico","Nicodime","Nicodemia","Nicodemo","NicÃ³demus","Nicodim","Nicol","Nicol","Nicola","Nicola",
            "Nicolaas","Nicolae","Nicolai","Nicolao","Nicolas","NicolÃ¡s","Nicolaus","Nicole","Nicolet","Nicoletta","Nicolette","Nicoline","Nicolle","Nicolo","Niegoslaw",
            "Niels","Niezamysl","Nigel","Nicholas","Nicholaus","Nik","Nika","Nikandr","Nikanor","Nike","NikÃ©","NikÃ©tÃ¡s","Niki","Niki","Nikifor",
            "Nikit","Nikita","Nikita","Nikki","Niklas","Niko","NikodÃ©m","NikodÃ©m","NikodÃ©ma","NikodÃ©ma","NikodÃ©mia","Nikodemus","NikodÃ©musz","Nikodija","Nikodim",
            "Nikodima","Nikol","Nikol","Nikola","Nikola","Nikolaj","Nikolaos","Nikolas","Nikolaus","Nikoleta","Nikoletta","Nikolina","Nikos","Nil","Nila",
            "Nilla","Nilo","Nils","Nina","Ninel","Nino","Nioba","Niobe","Niobe","Nirai","Nita","Noah","Noach","Noam","Nodin",
            "Noe","NoÃ©","Noel","NoÃ©l","Noil","Noela","Noelia","Noelia","NoÃ©lia","Noelie","Noelie","Noillie","Noema","Noemi","NoÃ©mi",
            "Noemie","NoÃ©mie","NoiUe","Nona","Nonna","Nora","Nora","Norah","Norberdina","Norbert","Norberta","Norberto","Noreen","Norene","Norik",
            "Norika","Noriko","Norma","Norman","Normand","Normann","Notburga","Octave","Octave","Octavia","Octavian","Octavianus","Octavie","Octavien","Octavio",
            "Octavius","Octavus","Od","Oda","Odana","Odd","Oddone","Ode","Ode","Odeta","Odett","Odetta","Odette","Odile","Odilia",
            "Odilie","Odina","Odmar","Odo","OdÃ³","Odoarda","OdolÃ¡n","Odolen","Odoljen","Odon","OdÃ³n","OdÃ³n","Odona","Ofelia","OfÃ©lia",
            "OfÃ©lie","OfeUia","Ofilia","Ofillia","Oksana","Oktavia","OktÃ¡via","Oktavian","OktaviÃ¡n","OktÃ¡viÃ¡n","Oktavie","OktÃ¡vie","Oktavij","Oktavij","Oktavij",
            "Oktavija","Oktavius","OktÃ¡vius","Oktaw","Oktawia","Oktawian","Oktawiusz","Ola","Olav","Olavo","Olbram","Olda","Oldrik","Oldoich","Oldoich",
            "Oldoicha","OldoiÅ¡ka","Oleandra","Oleandrija","Oleg","Oleksandr","Oleksandra","Oleksij","Olena","Olesja","Olga","Olga","Olimpia","Olimpiada","Olimpija",
            "Olin","Olina","Oliva","Olivi","Oliver","OlivÃ©r","Oliverio","Olivia","Olivie","Olivier","Olivija","Oljana","OlMa","OlManne","OlMe",
            "OlMero","Olof","Oluf","OluÅ¡e","Olympe","Olympia","Olympie","Omar","OmÃ¡r","Omer","Omero","Ondra","Ondoej","Ondoej","Ondoejka",
            "Onorata","Onorio","Onysij","Onysyfor","Onysym","Ophelia","OphÃ©lie","Ora","Orah","Oran","Orazio","OrbÃ¡n","Oren","Orest","Oresta",
            "Oreste","Orestej","Orestes","OresztÃ©sz","OrfÃ©","Orfea","Orfee","Orfej","Orfeo","Orfeus","Orfeusz","Orchidea","OrchidÃ©e","Ori","Oriana",
            "OriÃ¡na","Oriane","Orianna","Orianne","Orin","Orina","Orit","Orlan","Orlando","Orlin","Ornela","Ornella","Orora","OrphÃ©e","Orsola",
            "Ortensia","Ã“scar","Osip","Osipa","Oskar","Oskar","Oskara","Ostap","Osvald","Osvalda","Osvaldo","Oswald","Oswalda","Oswalde","Oswaldina",
            "Oswell","OszkÃ¡r","Oszvald","Ota","Ota","Otakar","Otakara","O?ho","Othon","Otilia","OtÃ­lia","Otilie","Otilija","Otmar","OtmÃ¡r",
            "Oto","Otokar","Otomar","Oton","Otta","Ottavia","Ottavio","Otte","Ottilia","Ottilie","Ottmar","Otto","Ottocar","Ottocare","Ottokar",
            "OttokÃ¡r","Ottomar","Otton","Ottone","Otylia","OtÃ½lie","Ovide","Ovidij","Ovidio","Ovidiu","Ovidius","OvÃ­dius","OvÃ­diusz","Owen","Owidiusz",
            "Oxana","OxÃ¡na","OzsÃ©b","Paavo","Pabiana","Pablo","Pacifico","Pacifik","PÃ¡drig","Paedar","PÃ¡l","Palmer","Palmira","Palmiro","PalmÃ­ro",
            "Palmyra","Paloma","PalÃ³ma","Pamela","Pamela","Panajot","Panajota","Panajotis","Pancrace","Pancracio","Pancratie","Pancratius","Pandora","PankrÃ¡c","Pankracy",
            "Pankrat","Pankratij","Pankratije","Pankratios","Pankratius","Pankraz","Pankrazio","Pantalejmon","Pantaleon","Pantaleon","PantalÃ©on","Pantaleone","Paola","Paolina","Paolo",
            "Par","Paraska","Paraskene","Paraskeva","Paraskovija","Parcifal","Parcival","Paride","Paris","Paris","Paris","Parisa","Parker","Parsival","Parzifal",
            "Parzival","Pascal","Pascale","Pascalina","Pascual","Paschalis","Paskal","Paskala","PaskÃ¡lia","Pasqua","Pasquale","Pasqualia","Pasqualina","PaszkÃ¡l","Patiycjusz",
            "PÃ¡tranÃ¡","Patrice","Patrice","Patricia","Patricia","Patricie","Patricij","Patricij","Patricije","Patricio","Patricius","Patricius","Patrick","Patrik","Patrika",
            "Patrikij","Patrikija","Patrizia","Patrizio","Patrizius","Patrycj","Patrycy","Patryk","Patty","Paul","Paula","Paule","Paulette","Paulin","Paulina",
            "PaulÃ­na","Paulini","Paullus","Paulo","Paulus","Paval","Pavao","Pavel","Pavla","Pavli","Pavlija","Pavlin","PavlÃ­n","Pavlina","Pavlina",
            "Pavlo","Pavlos","Pavol","Pawel","Peadair","Pearl","Pedro","Peggy","Pelageja","Pelagia","Pelagie","PÃ©lagie","Pelagija","Pelajia","PÃ©legrin",
            "Pelegrino","PÃ©lerin","Pelgrim","Pelhoim","Pellegrin","Pellegrino","Pena","Penelopa","Penelope","PÃ©nelopÃ©","Penka","Penko","Pentti","Pepino","Peppino",
            "Per","Perceval","Percival","Percy","Peregrin","PeregrÃ­n","PÃ©rÃ©grin","Peregrine","Peregrino","Peregrinus","Peregryn","Perez","Perchta","Pericle","Pericles",
            "Perikles","PeriklÃ©s","PeriklÃ©sz","Perkins","Perla","PerluÅ¡e","Persida","Perside","Persis","Perzida","Petar","Peter","Peter","Pitko","Petr",
            "Petra","Petrana","Petrija","Petrik","Petro","Petromila","Petronela","Petronella","Petronij","Petronije","Petronila","Petronilla","PÃ©tronille","Petronilo","Petronio",
            "Petronius","PetrÃ³nius","PetrÃ³niusz","Petros","Petru","Petrula","Petrumila","Petrunelja","Petrus","PetruÅ¡e","Petoi","Petoina","Petoini","Petula","Piva",
            "PivuÅ¡e","Phebe","Phffipp","Philbert","Philemon","Philiberte","Philip","Philippa","Philippe","Philippine","Philippos","Phillip","Philomela","Philomele","Philomena",
            "PhilomÃ©na","Philomene","Philomine","PhÃ³be","Phoebe","Phoenix","Phyllis","Pia","Piero","Pierre","Pierrette","Pietro","Pij","Pijo","Pilao",
            "Pilip","Pina","Pinelopi","Pio","Piotr","Piroska","Pirro","Pius","Piusz","Pjotr","Plato","Platon","PlatÃ³n","Platone","Policarpo",
            "Polikarp","PolikÃ¡rp","Polikarpo","Poliksemja","Poliksena","Polina","Polissena","Polixena","Polixeni","Polly","Pollyanna","Polyana","Polycarpe","Polycarpus","Polykarp",
            "Polykarpos","Polyxena","Polyxena","Polyxeni","Polyxeni","Polyxeni","Pomnin","Pomnina","Pomninka","PongrÃ¡c","Pravdoljub","Pravdomil","Pravdomila","Pravislav","Pravoinb",
            "Pravoljub","Pravomil","Pravomila","PravomÃ­r","Pravoslav","Pravoslava","Predrag","Preslava","Pribisav","Pribislav","Pribislava","Pribyslaw","Primislaus","Primislav","Prisca",
            "Priscila","PrisciUa","Priska","Priskilla","PriskiU","Procope","Procopio","ProcopiÃºs","Prochor","Prokop","Prokopa","Prokopi]","Prokopij","Prokopije","Prokopios",
            "Prokopka","Prosper","Prospero","PrÃ³spero","Protas","Protasij","Prvoslava","Przemyslaw","Przybyslawa","Poemek","Poemysl","Poemyslav","Poemyslava","Poibyslav","Poibyslava",
            "Pulcherija","Qinnton","Qinrino","Qscar","Quentin","Quido","Quincy","Quinetta","Quinn","Quintilien","Quirin","Quirinus","Qunitana","Racibor","Rada",
            "Radak","Radan","Radana","Rade","Radegast","Radek","Radeka","Raden","Radhost","Radie","Radigost","Radij","Radika","Radim","Radima",
            "Radimil","Radimir","RadimÃ­r","Radimira","RadimÃ­ra","Radin","Radislav","Radislava","Radivoj","Radivoje","Radka","Radko","Radmil","Radmila","Radogost",
            "Radohost","Radoje","Radojica","Radojka","Radola","Radolf","Radoljub","Radomil","Radomil","Radomila","Radomila","RadomÃ­r","RadomÃ­r","RadomÃ­ra","RadomÃ­ra",
            "Radomyr","Radon","Radoslav","Radoslava","Radoslaw","Radoslawa","RadoÅ¡","RadouÅ¡","Radovan","Radovana","Radovot","Radowan","Radslav","Radslava","Raissa",
            "Raduil","Radul","Radula","Radule","RaduÅ¡","RaduÅ¡e","RadÃºz","Radvan","Radvana","RadvÃ­t","Rae","Rafael","Rafaela","Rafaella","Rafail",
            "Rafaila","Rafal","Rafalyna","Raffaela","Raffaele","Raffaelo","Ragnar","Rahel","RÃ¡hel","RÃ¡chel","RÃ¡chel","Rachela","Rachele","Rachil","Rachila",
            "Rachilja","Raimondo","Raimund","Raimunda","Raimunde","Raimundo","Raina","Rainald","Raine","Rainer","Rainerio","Rainhard","Rainhold","Rainier","Raino",
            "Rainold","Raisa","Raissa","Rajka","Rajko","Rajmond","Rajmonda","Rajmund","Rajmunda","Rajna","Rajnald","Rajnold","Rajsa","Rakela","Ralf",
            "Ralica","Ralph","Raluca","Ramon","RamÃ³n","Ramona","RamÃ³na","Ran","RandÃ¡l","Randolf","Randolfo","Randolph","Randulf","Randulv","Randy",
            "Ranek","Ranieri","Ranieri","Ranjo","Ranko","Raoul","Raphael","Raphaela","Raquel","Rastisav","Rastislav","Rastislava","Ratiboo","Ratimir","RatimÃ­r",
            "Ratislav","Ratmir","RatmÃ­r","Ratoslav","Raul","Raven","Ray","Rayan","Raymond","Raymonde","Raymundo","Rayna","Rayner","Raynor","Rea",
            "Rebeca","Rebecca","RÃ©becca","Rebeka","Rebekah","Rebekka","Redmond","Redmund","Regan","Regina","Regina","Regina","Reginald","Reginaldo","Regini",
            "RÃ©gine","Regnar","RÃ©gnier","Reik","Reimund","Reinald","Reiner","Reingarda","Reinhard","Reinhilda","Reinhold","Reinold","Reinolf","Reka","Remig",
            "Remigio","Remigius","Remigiusz","Remo","Remus","RÃ©musz","Ren","Rena","Renard","Renat","RenÃ¡t","Renata","RenÃ¡ta","Renati","Renato",
            "Renatus","Renaud","Rene","RenÃ©","RenÃ©","RenÃ©e","Reni","Renia","Reno","Renzo","Reuben","Reweka","Reynaldo","Reynaldos","Reynard",
            "Reynold","Rhea","RhÃ©a","Rhian","Rhianon","Rhomylos","Rhona","RhÃ³xanÃ©","Ria","Riana","Rianna","Riano","Ricarda","Ricardo","Ricardus",
            "Riccarda","Riccardo","Rick","Rickard","Ricky","Rico","Rieard","Richard","Richard","Richarda","Richie","Rijk","Rik","Rikard","Rikarda",
            "Rikhard","Riley","Riley","Rina","Rinaldo","Rini","Rino","Rio","Risto","Rita","Ritchie","Riva","Rivka","Rjurik","Rob",
            "Robert","Robert","Roberta","Roberte","Roberto","Robertus","Robin","Robin","Robina","Robini","Robinson","Robrecht","Robyn","Rocco","Rock",
            "Rocky","Roda","Rodan","Roderick","Roderico","Roderich","Roderik","Roderyk","Rodger","Rodolfo","Rodolph","Rodolphe","Rodrigo","RodrigÃ³","Rodrigue",
            "Roeland","Roger","Rogerio","Rogerus","Roch","Rochus","Rok","Roka","Roko","Roksana","Roksolana","RÃ³kus","Rolan","RolÃ¡n","Roland",
            "RolÃ¡nd","Rolanda","Rolande","Rolando","Rolandus","Roleta","Rolf","Rolfe","Rolin","Rolland","Romain","Romaine","Roman","RomÃ¡n","Romana",
            "Romana","Romanija","Romano","Romanus","Romeo","Romeo","Romi","Romil","Romina","Romolo","Romuald","Romualda","Romualdo","Romul","RÃ³mulo",
            "Romulus","Romulusz","Romy","Rona","Rooa","Ronald","Ronaldo","Ronja","Ronny","Roque","Rory","Rosa","Rosalia","RosalÃ­a","Rosalie","Java",
            "Rosalind","Rosalinda","Rosalinde","Rosaline","Rosalio","Rosamond","Rosamund","Rosamunda","Rosamunde","Rosana","Rosanna","Rosaria","Rosarie","Rosario","Roscislaw",
            "Rose","Roseanna","Roselind","Rosemarie","Rosemonde","Rosen","Rosetta","Rosette","Rosina","Rosini","Rosita","Rosmunda","Ross","Rossa","Rostislav",
            "Rostislava","Rostyslav","Rostyslava","Roswith","Roswitha","Rovena","RovÃ©na","Rowdy","Rowena","Rowland","Roxana","RoxÃ¡na","Roxane","Roxanna","Roy",
            "Roza","RÃ³za","RÃ³za","Rozalia","RozÃ¡lia","RozÃ¡lie","Rozalija","Rozalinda","Rozamunda","Rozana","Rozanna","RozÃ¡rie","RozÃ¡rio","RozÃ¡rka","Rozaroj",
            "Rozeta","Rozina","Rozina","Rozita","Rozvita","Rozyna","RreÅ¡encija","Ruben","Ruben","Rubin","Ruby","Rudi","Rudiger","Rudina","Rudolf",
            "Rudolfa","Rudolfina","Rudolfina","Rudolfine","Rudolph","Rudolpha","Rudolphe","Rudolphina","Rudolphus","Ruf","Ruf","Rufin","Rufino","Rufinus","Rufus",
            "RÃºfus","RÃºfusz","Ruggero","Rumold","Runa","Rune","Rupert","Ruperto","Rupertus","Ruprecht","Rurik","Ruryk","Rusana","Ruslan","Ruslana",
            "RuszlÃ¡n","Rut","RÃºt","Ruta","Rutger","Ruth","Ruvini","RuÅ¾a","RuÅ¾ana","RuÅ¾ena","RuÅ¾ena","RuÅ¾ica","Ryan","Ryszard","Ryszarda",
            "Oehoo","Oehooka","Saba","SÃ¡ba","SabÃ¡s","Sabba","Sabel","Sabina","Sabina","Sabini","Sabrin","Sabrina","SÃ¡dko","Saffron","Sage",
            "Saima","Saimi","Salamon","Sally","Salmon","Saloma","Salomao","Salome","SalomÃ©","Salomea","Salomeja","Salomena","Salomo","Salomon","Salomon",
            "Salomone","Salomoja","Salvador","SalvÃ¡tor","SalvÃ¡tor","SalvÃ¡tore","Sam","Samanta","Samantha","Samar","Samara","Sammy","SÃ¡mo","Samojlo","Sampson",
            "Samson","Samson","Samuel","Samuel","Samuela","Samuele","Samuella","Samuil","Samuilo","Samy","Sana","SÃ¡ndor","Sandra","Sandrine","Sandro",
            "Sane","Sanela","SansÃ³n","SantÃ¡l","Santiago","Santino","Sapfo","Sara","SÃ¡ra","Sarah","Sarai","Sarolta","Saron","Sarra","Sasha",
            "Sasha","Sascha","Sascha","Saskia","Saskie","SaÅ¡a","SaÅ¡a","SaÅ¡e","SaÅ¡o","Saturni]","Saturnin","Saturnino","Saturninus","Saturnus","Saul",
            "Saul","Sava","Sava","SÃ¡va","SÃ¡va","Savana","Savanna","Savannah","Save","Savela","Savelij","Savelja","Saverio","Savina","Savka",
            "Savo","Sawa","Sawin","Saxana","Saxona","Sbislaus","Sbygneus","Scarlett","Scolastica","Scott","Sean","SÃ©bastia","Sebastian","SebastiÃ¡n","SebastiÃ¡n",
            "Sebastiana","SebastiÃ¡na","Sebastiane","Sebastiane","Sebastiano","Sebastianus","SÃ©bastien","Sebastinie","Sebastio","Sebestian","SebestyÃ©n","Sedrik","Segismundo","Seia","Seiya",
            "Sej","Selena","SelenÃ©","SÃ©lÃ©ne","Selina","Seline","Selwin","Selwyn","Sem","SemjÃ©n","Semjon","Senad","Senadin","Senta","Sentia",
            "Sepp","Serafim","Serafima","Serafin","SerafÃ­n","Serafina","SerafÃ­na","Serafino","Serafinus","Serafym","Seraph","SÃ©raphin","Seraphina","Seraphine","SÃ©raphine",
            "Seren","Serena","SÃ©rÃ©na","SÃ©rine","Sereno","Serenus","Serge","Sergej","Sergij","Sergije","Sergio","Sergiu","Sergius","Sergiusz","Serchio",
            "ServÃ¡c","Servacio","ServÃ¡cius","Servacoj","Servais","Servatius","Servaz","Servazio","Servio","Serwacy","Sevastiana","Sevastiani","Sevastija","Sevastijan","Sevastjan",
            "Sevastjana","Severian","Severin","SeverÃ­n","Severina","SeverÃ­na","Severino","Severinus","Severjan","Severyn","Seweryn","Shane","Shanel","Shanell","Shania",
            "Shannen","Shannon","Shari","Sharon","Sheila","Sheley","Shelley","Sheryl","Shilla","Shiloh","Shimon","Shoshanna","Shoshaunah","Scholastica","Scholastika",
            "Schulammit","Sian","Siana","Sibila","Sibille","SibiUa","Sibota","Sibyla","Sibylla","Sibylle","Sid","Sidney","Sidney","Sidoine","Sidon",
            "SidÃ³n","Sidonia","SidÃ³nia","Sidonie","Sidonija","Sidonio","Sidonius","Sidony","Siegfried","Sieglinda","Sieglinde","Siegmund","Sielinda","Sigfred","Sigfrid",
            "Sigfrid","SigfrÃ­d","Sigfrido","Sigismond","Sigismondo","Sigismund","Sigismundo","Sigismundus","Sigizmund","Siglinde","Sigmund","Sikandar","Sikst","Silas","Silka",
            "Silke","Silva","Silvain","Silvan","SilvÃ¡n","Silvana","SilvÃ¡na","Silvano","Silvanus","Silvestar","Silvester","Silvestr","Silvestra","Silvestoe","Silvia",
            "Silvie","Silvin","Silvius","SimeÃ¡o","Simeha","Simeon","SimeÃ³n","SimÃ©on","Simeona","Simeone","Simion","SiMj","SiMja","SiMje","Simo",
            "SiMo","Simon","Simon","Simona","Simone","Simone","Simoneta","Simonetta","Simonette","Simonida","Simson","Sinclair","Sindy","Sinikka","Sinkler",
            "SiobhÃ¡n","Sirio","Sirkka","Siro","Sisi","Sissi","Sissy","Sixt","Sixte","Sixto","Sixtus","Skarlet","Skarleta","Skolasztika","Slav",
            "SlÃ¡va","SlÃ¡va","SlÃ¡va","Slavata","SlÃ¡vek","Slaven","Slavena","Slavina","Slavi","Slaviboj","Slavibor","Slavij","Slavija","Slavimir","Slavin",
            "SlavÃ­na","Slavjana","SlÃ¡vka","SlÃ¡vka","SlÃ¡vko","Slavmyr","Slavoboj","Slavoj","Slavoje","Slavoljub","SlavolÃºb","Slavomil","Slavomila","SlavomÃ­r","SlavomÃ­r",
            "SlavomÃ­ra","SlavomÃ­ra","Slavomyr","SlavoÅ¡","Slaw","Slawa","Slawa","Slawka","Slawomir","Slawomira","Slobodan","Slobodana","Slobodanka","Slobodinka","Slobodna",
            "Smil","Smile","Smiljan","SneÅ¾ana","SneÅ¾anka","Sobislav","Sobislava","Sobieslaw","Sobieslawa","Socrate","Socrates","SÃ³crates","Sofia","Sofia","Sofian",
            "SofiÃ¡n","Sofie","Sofija","Sofijan","Sofio","Sofja","Sofrina","Sofronia","SofrÃ³nia","Sofronie","Sofronija","Sokrat","Sokrates","Sokratis","Solomon",
            "Solveig","Solveiga","Solvej","Sooa","Sonia","Sonja","Sonny","Sonya","Sophia","Sophie","Sophien","Sophius","Sopnronia","SÃ³ren","Sorley",
            "Soter","Sotera","Sotero","Sotir","Sotira","Sotiria","Sotirios","Sotirka","Spas","Spencer","Sperancie","Spiros","Spyros","Spytihniv","SpytimÃ­r",
            "Srdjan","SrdÅ¾an","Stacy","Staffan","StÃ¡na","Stanimir","StanimÃ­r","Stanislao","Stanislas","Stanislau","Stanislaus","Stanislav","Stanislava","Stanislaw","Stanislaw",
            "Stanislawa","Stanko","Stanley","Stas","Stasi","Stasij","StaÅ¡ek","Statis","Stavros","Staza","StÃ¡za","Stefan","Stefana","Stefania","StefÃ¡nia",
            "Stefanie","Stefanija","Stefanka","Stefano","Stefanus","Stefanyda","Steffi","Stefi","Stela","Stelia","Stelio","Stella","SteMa","SteMo","StepÃ¡n",
            "Stepanida","Stepanija","Stepanyda","Stephan","Stephana","StÃ©phane","StÃ©phane","Stephanie","StÃ©phanie","Stephanos","Stephanus","Stephen","Stevan","Steve","Steven",
            "StihÃ¡n","Stilijan","Stipe","Stjepan","Stoimir","Stojan","Stojimir","StojmÃ­r","Stomir","Stoezislav","StoezomÃ­r","Sufija","Sulamit","Sulamita","Sulamith",
            "Sulejka","Sulejman","Sulika","Susan","Susana","Susane","Susann","Susannah","Susanne","Susauna","Susette","Sussan","Suzan","Suzana","Suzanne",
            "SvÃ¡na","Svatava","Svatoboj","Svatoboj","Svatobor","SvatomÃ­r","SvatomÃ­r","SvatomÃ­ra","Svatopluk","Svatopluk","Svatoslav","Svatoslav","Svatoslava","SvatoÅ¡","SvatuÅ¡e",
            "Svebor","Svein","Svemil","Svemir","Sven","Svend","Sveno","Sverad","Sveslav","Svita","Svetana","Svetibor","Svetimir","Svetimira","Svetimirka",
            "SvetÃ­slav","Svetislava","Svitla","Svitla","Svitlana","Svitlana","SvitluÅ¡e","Sveto","Svetomir","Svetomira","Svetoslav","Svitoslav","Svetozar","SvetozÃ¡r","Svierad",
            "Svitlana","Svitozar","Svjatopolk","Svjatoslav","Swana","Swen","Swietobor","Swietomir","Swietopelk","Swietoslaw","Swietoslawa","Sybil","Sybila","Syd","Sydney",
            "Sydney","Sydonia","Sydoniusz","Syjato","Syjatogor","Sykstus","Sylfest","Sylva","Sylvain","Sylvest","Sylvester","Sylvestr","Sylvestre","Sylvie","Sylwester",
            "Sylwia","Sylwin","Sylwiusz","SyM","SyMa","Symeon","Symon","Szabina","SzalvÃ¡tor","Szandra","SzaniszlÃ³","Szarlota","Szczepan","Szczesny","Szende",
            "SzerÃ¡f","Szerafina","SzerÃ©na","SzerÃ©nusz","Szergiusz","SzervÃ¡c","Szeverin","Szibilla","SzidÃ³nia","Szigfrid","SzilvÃ¡na","SzilvÃ¡nusz","Szilveszter","Szilvius","SziMa",
            "Szimona","Szixtusz","SzofrÃ³nia","Szonja","SzvetlÃ¡na","Szymon","Szymona","Å alamoun","Å alamÃºn","Å alomoun","Å ana","Å Ã¡ndor","Å andy","Å andy","Å anel",
            "Å ansone","Å antal","Å Ã¡rka","Å arlota","Å avel","Å avol","Å ebestiÃ¡n","Å ebestiÃ¡na","Å ebÃ­o","Å elma","Å imon","Å imona","Å kolastika","Å lechtislav","Å ?asta",
            "Å tefan","Å tefÃ¡nia","Å tefanie","Å tefÃ¡nie","Å tipÃ¡n","Å tipÃ¡na","Å tipÃ¡nka","Tabea","Tabita","TÃ¡bita","Tabitha","Taddeo","Taddeus","TÃ¡dÃ©","TadeÃ¡Å¡",
            "Tadej","Tadeo","Tadeu","Tadeusz","Tadija","Taida","TainÃ¡","Tainara","Tais","Taisa","Taisia","Taisija","Taito","Takashi","TakaÅ¡i",
            "Takeo","Takeshi","Talinlah","Talisa","Talitha","Tallis","Tamara","TamÃ¡s","Tamika","Tamiko","Tamila","Tammy","TÃ¡oa","Tancred","Tancride",
            "Tancredi","Tancredo","Tania","Tanita","Tanitha","Tanja","Tankred","TankrÃ©d","Tano","Tanya","Tapani","Tara","Taras","Tarasij","Tarasije",
            "Tarasio","TarÃ¡z","Tarek","Tarik","Tarja","Tasia","Tasilo","Tasio","Taso","Tasso","TaszilÃ³","TaÅ¡o","Ta?Ã¡na","Tatiana","Tatiane",
            "Tatiani","Tatijana","Tatjana","TatjÃ¡na","Ta?jana","TauÃ¡","Tauan","Tavi","TavL","Taylor","Taylor","Tea","Tecla","Ted","Tekla",
            "Telma","Tena","Teo","Teobald","Teobaldo","Teodor","Teodora","Teodora","Teodorica","Teodorico","Teodorik","Teodorika","Teodoro","TeodorÃ³","Teodosia",
            "Teodosie","Teodosija","Teodosije","Teodosio","Teodoz","TeodÃ³zia","Teodozie","Teodozija","Teodozja","Teodozjusz","Teodozy","Teofan","Teofane","TeÃ³fanes","Teofanie",
            "Teofil","Teofila","Teofila","Teofilija","Teofilo","TeÃ³filo","Terancio","Terence","TÃ©rence","Terencio","Terencius","Terencjan","Terencjusz","TerÃ©ne","Terentij",
            "Terentius","Terenzio","Teresa","TÃ©rÃ©sa","Teresia","TerestyÃ©n","Terez","Tereza","TerÃ©zia","Terezie","Terezija","Terri","Terry","Terzo","Tess",
            "Tessa","Tetjana","Thaddaus","ThaddÃ©e","Thaddeus","ThadÃ©e","Thadeu","Thadeus","Thais","Thaisa","Thalia","ThÃ¡lie","ThÃ¡lie","Thanasis","Thassilo",
            "Thea","Thecla","Thicle","Thekla","Thelma","Theo","ThÃ©o","Theobald","Theobaldo","Theodebald","Theoderich","Theodor","Theodor","Theodora","Theodore",
            "Theodore","Theodore","Theodore","Theodoric","Theodorik","Theodorik","Theodorika","Theodoros","Theodorus","Theodooi","Theodosia","Theodosie","ThÃ©odosie","Theodosio","Theodosios",
            "Theodosius","Theofan","Theofanes","Theofanie","Theofil","Theofila","Theofilus","Theophania","Theophil","Theophila","ThÃ©ophile","Theophilus","Theopisti","Theresa","Therese",
            "ThÃ©rise","Theresia","Theudebaldo","Thibauld","Thibaut","Thomas","Thomas","Thomasa","Thomasina","Thomasine","Thomaz","Thorstein","Thorsten","Thurstan","Tiago",
            "Tiara","TibÃ¡d","Tiber","Tibere","Tiberij","Tiberio","Tiberiu","TibÃ©riusz","Tibold","Tibor","Tibora","Tibore","Tiburc","Tiburce","Tiburcij",
            "Tiburcio","Tiburcius","Tiburtius","Tiburzio","Ticia","Ticiana","Tiffany","Tiger","Tihana","Tichomil","Tichomir","Tichon","Tijana","TÃ­m","Timea",
            "TÃ­mea","Timo","Timofej","Timona","Timone","TimÃ³t","Timotea","Timotei","Timoteo","Timoteos","Timoteus","Timothea","TimothÃ©e","Timotheos","Timotheu",
            "Timotheus","Timothy","Timotije","Timur","Tina","Tino","Tinomil","Tinomir","Tisa","Tit","Tite","Tito","Titu","Titus","TÃ­tus",
            "Titusz","TiU","Tivadar","Tivurtij","Tizia","Tiziana","Tiziano","Tizio","Tlberius","TlhamÃ©r","TlchomÃ­r","Tlmon","Toar","Tobia","Tobias",
            "TobÃ­as","TÃ³biÃ¡s","Tobiasz","TobiÃ¡Å¡","Tobie","Tobija","Tobijas","Toby","Todor","TÃ³dor","Todora","Todosie","Tom","Toman","Tomanija",
            "Tomas","Tomasa","Tomasina","Tomassina","Tomasz","TomÃ¡Å¡","TomÃ¡Å¡","TomÃ¡Å¡","TomÃ¡Å¡ka","TomÃ¡zia","Tomi","Tomislaus","Tomislav","Tomislava","Tomislaw",
            "Tomislaw","Tomislawa","Tommaso","Tommi","Tommy","Toni","Toni","Tonia","TÃ³nino","Tonko","Tony","Tony","Tonya","Topi","Topias",
            "Tor","Tora","Torcuato","Torkvat","TorkvÃ¡t","Torkvato","Torna","Torquato","Torquatus","Torstein","Torsten","Torvid","Torvin","Tosca","Toska",
            "Toszka","Tovia","Tovija","Tracy","Tracy","Trajan","Traude","Traute","Travis","Trent","Trevor","Tristan","TristÃ¡n","Tristano","Tristanus",
            "Tristram","TrisztÃ¡n","Trix","Trixa","Trixi","Trixie","Trixy","Troy","Truda","Trude","Tryfon","Ttmotej","Tucker","Tudor","Tuho",
            "Tulia","Tulie","Tullia","Tullio","Tunde","TundÃ©r","Tuomi","Tuomo","Tuula","Tuulikki","Tworzyjan","Tyberiusz","Tyburcjusz","Tyburcy","Tyge",
            "Tychin","Tycho","Tychon","Tyke","Tymko","Tymofrj","Tymon","Tymoteusz","Tymur","TÃ½na","Tytus","Uberto","Udo","Ugo","Ula",
            "UlÃ¡szlÃ³","Ulf","Ulita","Uljan","Uljana","Ulla","Ulric","Ulrica","Ulrico","Ulrih","Ulrich","Ulrik","Ulrika","Ulrike","Ulrikka",
            "Ulrikke","Ulryka","Umar","Umberto","Una","Unislav","Unna","Upton","Urania","Urbain","Urban","Urban","Urbano","Urbanus","UriÃ¡Å¡",
            "ZlatoÅ¡","ZlatuÅ¡a","ZlatuÅ¡e","Zoa","Zoana","Zoe","ZoÃ©","Zofia","Zoi","Zoja","ZÃ³ja","ZÃ³lestin","ZÃ³lestine","ZÃ³lestinus","Zoltan",
            "ZoltÃ¡n","Zora","Zora","ZorÃ¡n","ZorÃ¡n","ZoranÃ¡","Zorian","Zorica","Zorika","Zorin","Zorina","Zorislav","Zorislava","Zorja","Zorjana",
            "Zorka","Zoro","Zoroslav","Zoroslava","Zoryna","Zosim","Zosima","Zosima","Zosimo","ZÃ³simo","Zosimus","Zosym","Zoya","Zozima","ZozimÃ©",
            "ZsadÃ¡ny","Zsaklin","Zsanett","Zseraldina","Zsigmond","ZsÃ³fia","Zsuzsauna","Zuleika","Zulejka","Zulika","Zuzana","Zuzanna","Zvezdan","Zvezdana","Zvezdomir",
            "Zvezdomira","Zvjezdan","Zvonimir","ZvonimÃ­r","Zvonimira","ZvonimÃ­ra","Zwonimir","Zygfryd","Zygmunt","Zyprian","Zyta","Å½akelina","Å½akelina","Å½akelina","Å½aklina",
            "Å½aklina","Å½anda","Å½anet","Å½aneta","Å½aneta","Å½anna","Å½anna","Å½arko","Å½aro","Å½dan","Å½dana","Å½elhnira","Å½elibor","Å½elimir","Å½elimÃ­r",
            "Å½elimÃ­ra","Å½elisav","Å½elisava","Å½elislav","Å½elislava","Å½elislaw","Å½elislawa","Å½elmÃ­r","Å½elmÃ­ra","Å½iboid","Å½igmund","Å½itomir","Å½itomÃ­r","Å½itomira","Å½itomÃ­ra",
            "Å½itoslav","Å½itoslava","Å½iva","Å½ivan","Å½ivana","Å½ivena","Å½ivena","Å½ivka","Å½ivko","Å½ivo","Å½ivodan","Å½ivodar","Å½ivojin","Å½ivomira","Å½ofia",
            "Å½ofie","Å½ywia"};

}
